/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Audience group type
*/
export enum AudienceGroupType {
    Upload = <any> 'UPLOAD',
    Click = <any> 'CLICK',
    Imp = <any> 'IMP',
    ChatTag = <any> 'CHAT_TAG',
    FriendPath = <any> 'FRIEND_PATH',
    Reservation = <any> 'RESERVATION',
    AppEvent = <any> 'APP_EVENT',
    VideoView = <any> 'VIDEO_VIEW',
    Webtraffic = <any> 'WEBTRAFFIC',
    ImageClick = <any> 'IMAGE_CLICK',
    RichmenuImp = <any> 'RICHMENU_IMP',
    RichmenuClick = <any> 'RICHMENU_CLICK'
}
