/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Failed type
 */

export type AudienceGroupFailedType =
  | "AUDIENCE_GROUP_AUDIENCE_INSUFFICIENT"
  | "INTERNAL_ERROR"
  | "null";
