/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AudienceGroupJobFailedType } from './audienceGroupJobFailedType';
import { AudienceGroupJobStatus } from './audienceGroupJobStatus';
import { AudienceGroupJobType } from './audienceGroupJobType';


/**
* Audience group job
*/
export type AudienceGroupJob =  { 
    /**
    * A job ID.
    */
    'audienceGroupJobId'?: number/**/;
    /**
    * An audience ID.
    */
    'audienceGroupId'?: number/**/;
    /**
    * The job\'s description.
    */
    'description'?: string/**/;
    /**
    */
    'type'?: AudienceGroupJobType/**/;
    /**
    */
    'jobStatus'?: AudienceGroupJobStatus/**/;
    /**
    */
    'failedType'?: AudienceGroupJobFailedType/**/;
    /**
    * The number of accounts (recipients) that were added or removed.
    */
    'audienceCount'?: number/**/;
    /**
    * When the job was created (in UNIX time).
    */
    'created'?: number/**/;
}

export namespace AudienceGroupJob {
}
