/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Audience group type
 */

export type AudienceGroupType =
  | "UPLOAD"
  | "CLICK"
  | "IMP"
  | "CHAT_TAG"
  | "FRIEND_PATH"
  | "RESERVATION"
  | "APP_EVENT"
  | "VIDEO_VIEW"
  | "WEBTRAFFIC"
  | "IMAGE_CLICK"
  | "RICHMENU_IMP"
  | "RICHMENU_CLICK"
  | "POP_AD_IMP";
