/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';

/**
* Create audience for impression-based retargeting
*/
export type CreateImpBasedAudienceGroupRequest = {
    /**
    * The audience\'s name. This is case-insensitive, meaning `AUDIENCE` and `audience` are considered identical. Max character limit: 120 
    */
    'description'?: string/**/;
    /**
    * The request ID of a broadcast or narrowcast message sent in the past 60 days. Each Messaging API request has a request ID. 
    */
    'requestId'?: string/**/;
}

