/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';
import { Audience } from './audience';


/**
* Create audience for uploading user IDs (by JSON)
*/
export type CreateAudienceGroupRequest =  { 
    /**
    * The audience\'s name. This is case-insensitive, meaning AUDIENCE and audience are considered identical. Max character limit: 120 
    */
    'description'?: string/**/;
    /**
    * To specify recipients by IFAs: set true. To specify recipients by user IDs: set false or omit isIfaAudience property. 
    */
    'isIfaAudience'?: boolean/**/;
    /**
    * The description to register for the job (in jobs[].description). 
    */
    'uploadDescription'?: string/**/;
    /**
    * An array of user IDs or IFAs. Max number: 10,000 
    */
    'audiences'?: Array<Audience>/**/;
}

