/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AudienceGroupAuthorityLevel } from './audienceGroupAuthorityLevel';

/**
* Get the authority level of the audience
*/
export class GetAudienceGroupAuthorityLevelResponse {
    'authorityLevel'?: AudienceGroupAuthorityLevel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "authorityLevel",
            "baseName": "authorityLevel",
            "type": "AudienceGroupAuthorityLevel"
        }    ];

    static getAttributeTypeMap() {
        return GetAudienceGroupAuthorityLevelResponse.attributeTypeMap;
    }
}

export namespace GetAudienceGroupAuthorityLevelResponse {
}
