/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Rename an audience
 */
export type UpdateAudienceGroupDescriptionRequest = {
  /**
   * The audience\'s name. This is case-insensitive, meaning AUDIENCE and audience are considered identical. Max character limit: 120
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#set-description-audience-group">description Documentation</a>
   */
  description?: string /**/;
};
