/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LotteryAcquisitionConditionResponse } from "./models.js";
import { NormalAcquisitionConditionResponse } from "./models.js";
import { ReferralAcquisitionConditionResponse } from "./models.js";

export type AcquisitionConditionResponse =
  | LotteryAcquisitionConditionResponse // lottery
  | NormalAcquisitionConditionResponse // normal
  | ReferralAcquisitionConditionResponse; // referral

export type AcquisitionConditionResponseBase = {
  /**
   * Determines how the coupon is distributed or used.
   */
  type: string /**/;
};
