/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LotteryAcquisitionConditionRequest } from "./models.js";
import { NormalAcquisitionConditionRequest } from "./models.js";

export type AcquisitionConditionRequest =
  | LotteryAcquisitionConditionRequest // lottery
  | NormalAcquisitionConditionRequest; // normal

export type AcquisitionConditionRequestBase = {
  /**
   * Determines how the coupon is distributed or used.
   */
  type: string /**/;
};
