/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum AgeDemographic {
    _15 = <any> 'age_15',
    _20 = <any> 'age_20',
    _25 = <any> 'age_25',
    _30 = <any> 'age_30',
    _35 = <any> 'age_35',
    _40 = <any> 'age_40',
    _45 = <any> 'age_45',
    _50 = <any> 'age_50'
}
