/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MentionTarget } from "./mentionTarget.js";

import { MentionTargetBase } from "./models.js";

/**
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#text-message-v2-mentionee-all">https://developers.line.biz/en/reference/messaging-api/#text-message-v2-mentionee-all</a>
 */
export type AllMentionTarget = MentionTargetBase & {
  type: "all";
};
