/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AreaDemographic } from "./areaDemographic";
import { DemographicFilter } from "./demographicFilter";

import { DemographicFilterBase } from "./models";

export type AreaDemographicFilter = DemographicFilterBase & {
  type: "area";
  /**
   */
  oneOf?: Array<AreaDemographic> /**/;
};
