/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type BotInfoResponse =  { 
    /**
    * Bot\'s user ID
    */
    'userId': string/**/;
    /**
    * Bot\'s basic ID
    */
    'basicId': string/**/;
    /**
    * Bot\'s premium ID. Not included in the response if the premium ID isn\'t set.
    */
    'premiumId'?: string/**/;
    /**
    * Bot\'s display name
    */
    'displayName': string/**/;
    /**
    * Profile image URL. `https` image URL. Not included in the response if the bot doesn\'t have a profile image.
    */
    'pictureUrl'?: string/**/;
    /**
    * Chat settings set in the LINE Official Account Manager. One of:  `chat`: Chat is set to \"On\". `bot`: Chat is set to \"Off\". 
    */
    'chatMode': BotInfoResponse.ChatModeEnum/**/;
    /**
    * Automatic read setting for messages. If the chat is set to \"Off\", auto is returned. If the chat is set to \"On\", manual is returned.  `auto`: Auto read setting is enabled. `manual`: Auto read setting is disabled.  
    */
    'markAsReadMode': BotInfoResponse.MarkAsReadModeEnum/**/;
}

export namespace BotInfoResponse {
    export enum ChatModeEnum {
        Chat = <any> 'chat',
        Bot = <any> 'bot'
    }
    export enum MarkAsReadModeEnum {
        Auto = <any> 'auto',
        Manual = <any> 'manual'
    }
}
