/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response object returned after creating a coupon. Contains the coupon ID.
 */
export type CouponCreateResponse = {
  /**
   * Unique identifier of the coupon.
   */
  couponId: string /**/;
};
