/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Message } from "./message.js";
import { QuickReply } from "./quickReply.js";
import { Sender } from "./sender.js";

import { MessageBase } from "./models.js";

export type CouponMessage = MessageBase & {
  type: "coupon";
  /**
   * Unique identifier of the coupon.
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#coupon-message">couponId Documentation</a>
   */
  couponId: string /**/;
  /**
   * Delivery route tag information. It can be used for analysis in LINE OA Manager.
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#coupon-message">deliveryTag Documentation</a>
   */
  deliveryTag?: string /**/;
};
