/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Summary information about a coupon, used in coupon lists.
 */
export type CouponListResponse = {
  /**
   * Unique identifier of the coupon.
   */
  couponId: string /**/;
  /**
   * Title of the coupon. Displayed in the coupon list.
   */
  title: string /**/;
};
