/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';

export type CreateRichMenuAliasRequest = {
    /**
    * Rich menu alias ID, which can be any ID, unique for each channel.
    */
    'richMenuAliasId': string/**/;
    /**
    * The rich menu ID to be associated with the rich menu alias.
    */
    'richMenuId': string/**/;
}

