/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DiscountPriceInfoResponse } from "./discountPriceInfoResponse.js";

import { DiscountPriceInfoResponseBase } from "./models.js";

export type DiscountFixedPriceInfoResponse = DiscountPriceInfoResponseBase & {
  type: "fixed";
  /**
   * Currency code (e.g., JPY, THB, TWD).
   */
  currency?: DiscountFixedPriceInfoResponse.CurrencyEnum /**/;
  /**
   */
  fixedAmount?: number /**/;
};

export namespace DiscountFixedPriceInfoResponse {
  export type CurrencyEnum = "JPY" | "THB" | "TWD";
}
