/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FlexBoxBackground } from "./flexBoxBackground.js";

import { FlexBoxBackgroundBase } from "./models.js";

export type FlexBoxLinearGradient = FlexBoxBackgroundBase & {
  type: "linearGradient";
  /**
   */
  angle?: string /**/;
  /**
   */
  startColor?: string /**/;
  /**
   */
  endColor?: string /**/;
  /**
   */
  centerColor?: string /**/;
  /**
   */
  centerPosition?: string /**/;
};
