/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type GetAggregationUnitUsageResponse = {
  /**
   * Number of aggregation units used this month.
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-number-of-units-used-this-month">numOfCustomAggregationUnits Documentation</a>
   */
  numOfCustomAggregationUnits: number /**/;
};
