/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Subscription } from "./subscription.js";

/**
 * A user\'s membership subscription status
 */
export type GetMembershipSubscriptionResponse = {
  /**
   * List of subscription information
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-a-users-membership-subscription-status">subscriptions Documentation</a>
   */
  subscriptions: Array<Subscription> /**/;
};
