/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';

/**
* Transcoding response
*/
export class GetMessageContentTranscodingResponse {
    /**
    * The preparation status. One of:  `processing`: Preparing to get content. `succeeded`: Ready to get the content. You can get the content sent by users. `failed`: Failed to prepare to get the content. 
    */
    'status': GetMessageContentTranscodingResponse.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "GetMessageContentTranscodingResponse.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return GetMessageContentTranscodingResponse.attributeTypeMap;
    }
}

export namespace GetMessageContentTranscodingResponse {
    export enum StatusEnum {
        Processing = <any> 'processing',
        Succeeded = <any> 'succeeded',
        Failed = <any> 'failed'
    }
}
