/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GroupSummaryResponse =  { 
    /**
    * Group ID
    */
    'groupId': string/**/;
    /**
    * Group name
    */
    'groupName': string/**/;
    /**
    * Group icon URL. Not included in the response if the user doesn\'t set a group profile icon.
    */
    'pictureUrl'?: string/**/;
}

