/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';
import { ImagemapArea } from './imagemapArea';

export class ImagemapAction {
    'type': string;
    'area'?: ImagemapArea;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "area",
            "baseName": "area",
            "type": "ImagemapArea"
        }    ];

    static getAttributeTypeMap() {
        return ImagemapAction.attributeTypeMap;
    }
}

