/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';
import { ImagemapArea } from './imagemapArea';

import { MessageImagemapAction } from './models';
import { URIImagemapAction } from './models';

export type ImagemapAction =
        | MessageImagemapAction // message
        | URIImagemapAction // uri
;

export type ImagemapActionBase =  { 
    /**
    */
    'type': string/**/;
    /**
    */
    'area'?: ImagemapArea/**/;
}

