/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ImagemapAction } from "./imagemapAction.js";
import { ImagemapBaseSize } from "./imagemapBaseSize.js";
import { ImagemapVideo } from "./imagemapVideo.js";
import { Message } from "./message.js";
import { QuickReply } from "./quickReply.js";
import { Sender } from "./sender.js";

import { MessageBase } from "./models.js";

/**
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#imagemap-message">https://developers.line.biz/en/reference/messaging-api/#imagemap-message</a>
 */
export type ImagemapMessage = MessageBase & {
  type: "imagemap";

  baseUrl: string;
  altText: string;
  baseSize: ImagemapBaseSize;
  actions: Array<ImagemapAction>;
  video?: ImagemapVideo;
};
