/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#issue-link-token">https://developers.line.biz/en/reference/messaging-api/#issue-link-token</a>
 */
export type IssueLinkTokenResponse = {
  /**
   * Link token. Link tokens are valid for 10 minutes and can only be used once.
   */
  linkToken: string;
};
