/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Message } from "./message.js";
import { QuickReply } from "./quickReply.js";
import { Sender } from "./sender.js";

import { MessageBase } from "./models.js";

export type LocationMessage = MessageBase & {
  type: "location";
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#location-message">title Documentation</a>
   */
  title: string /**/;
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#location-message">address Documentation</a>
   */
  address: string /**/;
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#location-message">latitude Documentation</a>
   */
  latitude: number /**/;
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#location-message">longitude Documentation</a>
   */
  longitude: number /**/;
};
