/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#mark-as-read-request-body">https://developers.line.biz/en/reference/messaging-api/#mark-as-read-request-body</a>
 */
export type MarkMessagesAsReadByTokenRequest = {
  /**
   * Token used to mark messages as read.
   */
  markAsReadToken: string;
};
