/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuickReply } from "./quickReply";
import { Sender } from "./sender";

import { AudioMessage } from "./models";
import { FlexMessage } from "./models";
import { ImageMessage } from "./models";
import { ImagemapMessage } from "./models";
import { LocationMessage } from "./models";
import { StickerMessage } from "./models";
import { TemplateMessage } from "./models";
import { TextMessage } from "./models";
import { VideoMessage } from "./models";

export type Message =
  | AudioMessage // audio
  | FlexMessage // flex
  | ImageMessage // image
  | ImagemapMessage // imagemap
  | LocationMessage // location
  | StickerMessage // sticker
  | TemplateMessage // template
  | TextMessage // text
  | VideoMessage // video
  | UnknownMessage;

export type UnknownMessage = MessageBase & {
  [key: string]: unknown;
};

export type MessageBase = {
  /**
   * Type of message
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#message-common-properties">type Documentation</a>
   */
  type: string /**/;
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#message-common-properties">quickReply Documentation</a>
   */
  quickReply?: QuickReply /**/;
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#message-common-properties">sender Documentation</a>
   */
  sender?: Sender /**/;
};
