export * from './action';
export * from './ageDemographic';
export * from './ageDemographicFilter';
export * from './altUri';
export * from './appTypeDemographic';
export * from './appTypeDemographicFilter';
export * from './areaDemographic';
export * from './areaDemographicFilter';
export * from './audienceMatchMessagesRequest';
export * from './audienceRecipient';
export * from './audioMessage';
export * from './botInfoResponse';
export * from './broadcastRequest';
export * from './buttonsTemplate';
export * from './cameraAction';
export * from './cameraRollAction';
export * from './carouselColumn';
export * from './carouselTemplate';
export * from './chatReference';
export * from './confirmTemplate';
export * from './createRichMenuAliasRequest';
export * from './datetimePickerAction';
export * from './demographicFilter';
export * from './emoji';
export * from './errorDetail';
export * from './errorResponse';
export * from './filter';
export * from './flexBlockStyle';
export * from './flexBox';
export * from './flexBoxBackground';
export * from './flexBoxLinearGradient';
export * from './flexBubble';
export * from './flexBubbleStyles';
export * from './flexButton';
export * from './flexCarousel';
export * from './flexComponent';
export * from './flexContainer';
export * from './flexFiller';
export * from './flexIcon';
export * from './flexImage';
export * from './flexMessage';
export * from './flexSeparator';
export * from './flexSpan';
export * from './flexText';
export * from './flexVideo';
export * from './genderDemographic';
export * from './genderDemographicFilter';
export * from './getAggregationUnitNameListResponse';
export * from './getAggregationUnitUsageResponse';
export * from './getFollowersResponse';
export * from './getMessageContentTranscodingResponse';
export * from './getWebhookEndpointResponse';
export * from './groupMemberCountResponse';
export * from './groupSummaryResponse';
export * from './groupUserProfileResponse';
export * from './imageCarouselColumn';
export * from './imageCarouselTemplate';
export * from './imageMessage';
export * from './imagemapAction';
export * from './imagemapArea';
export * from './imagemapBaseSize';
export * from './imagemapExternalLink';
export * from './imagemapMessage';
export * from './imagemapVideo';
export * from './issueLinkTokenResponse';
export * from './limit';
export * from './locationAction';
export * from './locationMessage';
export * from './markMessagesAsReadRequest';
export * from './membersIdsResponse';
export * from './message';
export * from './messageAction';
export * from './messageImagemapAction';
export * from './messageQuotaResponse';
export * from './multicastRequest';
export * from './narrowcastProgressResponse';
export * from './narrowcastRequest';
export * from './numberOfMessagesResponse';
export * from './operatorDemographicFilter';
export * from './operatorRecipient';
export * from './pnpMessagesRequest';
export * from './postbackAction';
export * from './pushMessageRequest';
export * from './pushMessageResponse';
export * from './quickReply';
export * from './quickReplyItem';
export * from './quotaConsumptionResponse';
export * from './quotaType';
export * from './recipient';
export * from './redeliveryRecipient';
export * from './replyMessageRequest';
export * from './replyMessageResponse';
export * from './richMenuAliasListResponse';
export * from './richMenuAliasResponse';
export * from './richMenuArea';
export * from './richMenuBatchLinkOperation';
export * from './richMenuBatchOperation';
export * from './richMenuBatchProgressPhase';
export * from './richMenuBatchProgressResponse';
export * from './richMenuBatchRequest';
export * from './richMenuBatchUnlinkAllOperation';
export * from './richMenuBatchUnlinkOperation';
export * from './richMenuBounds';
export * from './richMenuBulkLinkRequest';
export * from './richMenuBulkUnlinkRequest';
export * from './richMenuIdResponse';
export * from './richMenuListResponse';
export * from './richMenuRequest';
export * from './richMenuResponse';
export * from './richMenuSize';
export * from './richMenuSwitchAction';
export * from './roomMemberCountResponse';
export * from './roomUserProfileResponse';
export * from './sender';
export * from './sentMessage';
export * from './setWebhookEndpointRequest';
export * from './stickerMessage';
export * from './subscriptionPeriodDemographic';
export * from './subscriptionPeriodDemographicFilter';
export * from './template';
export * from './templateMessage';
export * from './testWebhookEndpointRequest';
export * from './testWebhookEndpointResponse';
export * from './textMessage';
export * from './uRIAction';
export * from './uRIImagemapAction';
export * from './updateRichMenuAliasRequest';
export * from './userProfileResponse';
export * from './validateMessageRequest';
export * from './videoMessage';

import * as fs from 'fs';

export interface RequestDetailedFile {
    value: Buffer;
    options?: {
        filename?: string;
        contentType?: string;
    }
}

export type RequestFile = string | Buffer | fs.ReadStream | RequestDetailedFile;


import { Action } from './action';
import { AgeDemographic } from './ageDemographic';
import { AgeDemographicFilter } from './ageDemographicFilter';
import { AltUri } from './altUri';
import { AppTypeDemographic } from './appTypeDemographic';
import { AppTypeDemographicFilter } from './appTypeDemographicFilter';
import { AreaDemographic } from './areaDemographic';
import { AreaDemographicFilter } from './areaDemographicFilter';
import { AudienceMatchMessagesRequest } from './audienceMatchMessagesRequest';
import { AudienceRecipient } from './audienceRecipient';
import { AudioMessage } from './audioMessage';
import { BotInfoResponse } from './botInfoResponse';
import { BroadcastRequest } from './broadcastRequest';
import { ButtonsTemplate } from './buttonsTemplate';
import { CameraAction } from './cameraAction';
import { CameraRollAction } from './cameraRollAction';
import { CarouselColumn } from './carouselColumn';
import { CarouselTemplate } from './carouselTemplate';
import { ChatReference } from './chatReference';
import { ConfirmTemplate } from './confirmTemplate';
import { CreateRichMenuAliasRequest } from './createRichMenuAliasRequest';
import { DatetimePickerAction } from './datetimePickerAction';
import { DemographicFilter } from './demographicFilter';
import { Emoji } from './emoji';
import { ErrorDetail } from './errorDetail';
import { ErrorResponse } from './errorResponse';
import { Filter } from './filter';
import { FlexBlockStyle } from './flexBlockStyle';
import { FlexBox } from './flexBox';
import { FlexBoxBackground } from './flexBoxBackground';
import { FlexBoxLinearGradient } from './flexBoxLinearGradient';
import { FlexBubble } from './flexBubble';
import { FlexBubbleStyles } from './flexBubbleStyles';
import { FlexButton } from './flexButton';
import { FlexCarousel } from './flexCarousel';
import { FlexComponent } from './flexComponent';
import { FlexContainer } from './flexContainer';
import { FlexFiller } from './flexFiller';
import { FlexIcon } from './flexIcon';
import { FlexImage } from './flexImage';
import { FlexMessage } from './flexMessage';
import { FlexSeparator } from './flexSeparator';
import { FlexSpan } from './flexSpan';
import { FlexText } from './flexText';
import { FlexVideo } from './flexVideo';
import { GenderDemographic } from './genderDemographic';
import { GenderDemographicFilter } from './genderDemographicFilter';
import { GetAggregationUnitNameListResponse } from './getAggregationUnitNameListResponse';
import { GetAggregationUnitUsageResponse } from './getAggregationUnitUsageResponse';
import { GetFollowersResponse } from './getFollowersResponse';
import { GetMessageContentTranscodingResponse } from './getMessageContentTranscodingResponse';
import { GetWebhookEndpointResponse } from './getWebhookEndpointResponse';
import { GroupMemberCountResponse } from './groupMemberCountResponse';
import { GroupSummaryResponse } from './groupSummaryResponse';
import { GroupUserProfileResponse } from './groupUserProfileResponse';
import { ImageCarouselColumn } from './imageCarouselColumn';
import { ImageCarouselTemplate } from './imageCarouselTemplate';
import { ImageMessage } from './imageMessage';
import { ImagemapAction } from './imagemapAction';
import { ImagemapArea } from './imagemapArea';
import { ImagemapBaseSize } from './imagemapBaseSize';
import { ImagemapExternalLink } from './imagemapExternalLink';
import { ImagemapMessage } from './imagemapMessage';
import { ImagemapVideo } from './imagemapVideo';
import { IssueLinkTokenResponse } from './issueLinkTokenResponse';
import { Limit } from './limit';
import { LocationAction } from './locationAction';
import { LocationMessage } from './locationMessage';
import { MarkMessagesAsReadRequest } from './markMessagesAsReadRequest';
import { MembersIdsResponse } from './membersIdsResponse';
import { Message } from './message';
import { MessageAction } from './messageAction';
import { MessageImagemapAction } from './messageImagemapAction';
import { MessageQuotaResponse } from './messageQuotaResponse';
import { MulticastRequest } from './multicastRequest';
import { NarrowcastProgressResponse } from './narrowcastProgressResponse';
import { NarrowcastRequest } from './narrowcastRequest';
import { NumberOfMessagesResponse } from './numberOfMessagesResponse';
import { OperatorDemographicFilter } from './operatorDemographicFilter';
import { OperatorRecipient } from './operatorRecipient';
import { PnpMessagesRequest } from './pnpMessagesRequest';
import { PostbackAction } from './postbackAction';
import { PushMessageRequest } from './pushMessageRequest';
import { PushMessageResponse } from './pushMessageResponse';
import { QuickReply } from './quickReply';
import { QuickReplyItem } from './quickReplyItem';
import { QuotaConsumptionResponse } from './quotaConsumptionResponse';
import { QuotaType } from './quotaType';
import { Recipient } from './recipient';
import { RedeliveryRecipient } from './redeliveryRecipient';
import { ReplyMessageRequest } from './replyMessageRequest';
import { ReplyMessageResponse } from './replyMessageResponse';
import { RichMenuAliasListResponse } from './richMenuAliasListResponse';
import { RichMenuAliasResponse } from './richMenuAliasResponse';
import { RichMenuArea } from './richMenuArea';
import { RichMenuBatchLinkOperation } from './richMenuBatchLinkOperation';
import { RichMenuBatchOperation } from './richMenuBatchOperation';
import { RichMenuBatchProgressPhase } from './richMenuBatchProgressPhase';
import { RichMenuBatchProgressResponse } from './richMenuBatchProgressResponse';
import { RichMenuBatchRequest } from './richMenuBatchRequest';
import { RichMenuBatchUnlinkAllOperation } from './richMenuBatchUnlinkAllOperation';
import { RichMenuBatchUnlinkOperation } from './richMenuBatchUnlinkOperation';
import { RichMenuBounds } from './richMenuBounds';
import { RichMenuBulkLinkRequest } from './richMenuBulkLinkRequest';
import { RichMenuBulkUnlinkRequest } from './richMenuBulkUnlinkRequest';
import { RichMenuIdResponse } from './richMenuIdResponse';
import { RichMenuListResponse } from './richMenuListResponse';
import { RichMenuRequest } from './richMenuRequest';
import { RichMenuResponse } from './richMenuResponse';
import { RichMenuSize } from './richMenuSize';
import { RichMenuSwitchAction } from './richMenuSwitchAction';
import { RoomMemberCountResponse } from './roomMemberCountResponse';
import { RoomUserProfileResponse } from './roomUserProfileResponse';
import { Sender } from './sender';
import { SentMessage } from './sentMessage';
import { SetWebhookEndpointRequest } from './setWebhookEndpointRequest';
import { StickerMessage } from './stickerMessage';
import { SubscriptionPeriodDemographic } from './subscriptionPeriodDemographic';
import { SubscriptionPeriodDemographicFilter } from './subscriptionPeriodDemographicFilter';
import { Template } from './template';
import { TemplateMessage } from './templateMessage';
import { TestWebhookEndpointRequest } from './testWebhookEndpointRequest';
import { TestWebhookEndpointResponse } from './testWebhookEndpointResponse';
import { TextMessage } from './textMessage';
import { URIAction } from './uRIAction';
import { URIImagemapAction } from './uRIImagemapAction';
import { UpdateRichMenuAliasRequest } from './updateRichMenuAliasRequest';
import { UserProfileResponse } from './userProfileResponse';
import { ValidateMessageRequest } from './validateMessageRequest';
import { VideoMessage } from './videoMessage';

