/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Message } from "./message.js";

/**
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#send-multicast-message">https://developers.line.biz/en/reference/messaging-api/#send-multicast-message</a>
 */
export type MulticastRequest = {
  /**
   * Messages to send
   * @minItems 1
   * @maxItems 5
   */
  messages: Array<Message>;
  /**
   * Array of user IDs. Use userId values which are returned in webhook event objects. Do not use LINE IDs found on LINE.
   * @minItems 1
   * @maxItems 500
   */
  to: Array<string>;
  /**
   * `true`: The user doesn’t receive a push notification when a message is sent. `false`: The user receives a push notification when the message is sent (unless they have disabled push notifications in LINE and/or their device). The default value is false.
   * @default false
   */
  notificationDisabled?: boolean;
  /**
   * Name of aggregation unit. Case-sensitive.
   * @maxItems 1
   */
  customAggregationUnits?: Array<string>;
};
