/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DemographicFilter } from "./demographicFilter.js";

import { DemographicFilterBase } from "./models.js";

export type OperatorDemographicFilter = DemographicFilterBase & {
  type: "operator";
  /**
   */
  and?: Array<DemographicFilter> /**/;
  /**
   */
  or?: Array<DemographicFilter> /**/;
  /**
   */
  not?: DemographicFilter /**/;
};
