/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Recipient } from './recipient';

export class OperatorRecipient extends Recipient {
    /**
    * Create a new recipient object by taking the logical conjunction (AND) of the specified array of recipient objects. 
    */
    'and'?: Array<Recipient>;
    /**
    * Create a new recipient object by taking the logical disjunction (OR) of the specified array of recipient objects. 
    */
    'or'?: Array<Recipient>;
    'not'?: Recipient;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "and",
            "baseName": "and",
            "type": "Array<Recipient>"
        },
        {
            "name": "or",
            "baseName": "or",
            "type": "Array<Recipient>"
        },
        {
            "name": "not",
            "baseName": "not",
            "type": "Recipient"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(OperatorRecipient.attributeTypeMap);
    }
}

