/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @see <a href="https://developers.line.biz/en/reference/line-notification-messages/#send-line-notification-message-template-items">https://developers.line.biz/en/reference/line-notification-messages/#send-line-notification-message-template-items</a>
 */
export type PnpTemplatedItem = {
  /**
   * Specify the key of the item you want to include. For available keys, see https://developers.line.biz/en/docs/partner-docs/line-notification-messages/template/#items
   */
  itemKey: string;
  /**
   * String to be displayed as the value of the item.
   * Maximum length: 300
   */
  content: string;
};
