/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Action } from "./action.js";

export type QuickReplyItem = {
  /**
   * URL of the icon that is displayed at the beginning of the button
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#items-object">imageUrl Documentation</a>
   */
  imageUrl?: string /**/;
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#items-object">action Documentation</a>
   */
  action?: Action /**/;
  /**
   * `action`
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#items-object">type Documentation</a>
   */
  type?: string /* = 'action'*/;
};
