/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Action } from "./action.js";

/**
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#items-object">https://developers.line.biz/en/reference/messaging-api/#items-object</a>
 */
export type QuickReplyItem = {
  /**
   * URL of the icon that is displayed at the beginning of the button
   * @maxLength 2000
   */
  imageUrl?: string;
  action?: Action;
  /**
   * `action`
   * @default 'action'
   */
  type?: string;
};
