/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type QuotaConsumptionResponse = {
  /**
   * The number of sent messages in the current month
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-consumption">totalUsage Documentation</a>
   */
  totalUsage: number /**/;
};
