/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AudienceRecipient } from "./models.js";
import { OperatorRecipient } from "./models.js";
import { RedeliveryRecipient } from "./models.js";

export type Recipient =
  | AudienceRecipient // audience
  | OperatorRecipient // operator
  | RedeliveryRecipient; // redelivery

/**
 * Recipient
 */
export type RecipientBase = {
  /**
   * Type of recipient
   */
  type?: string /**/;
};
