/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';


/**
* Rich menu bounds
*/
export type RichMenuBounds = {
    /**
    * Horizontal position relative to the top-left corner of the area.
    */
    'x'?: number/**/;
    /**
    * Vertical position relative to the top-left corner of the area.
    */
    'y'?: number/**/;
    /**
    * Width of the area.
    */
    'width'?: number/**/;
    /**
    * Height of the area.
    */
    'height'?: number/**/;
}

