/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';

/**
* Rich menu operation object represents the batch operation to the rich menu linked to the user.
*/
export type RichMenuBatchOperation = {
    /**
    * The type of operation to the rich menu linked to the user. One of link, unlink, or unlinkAll.
    */
    'type': string/**/;
}

