/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type RichMenuAliasResponse = {
  /**
   * Rich menu alias ID.
   */
  richMenuAliasId: string /**/;
  /**
   * The rich menu ID associated with the rich menu alias.
   */
  richMenuId: string /**/;
};
