/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Action } from "./action.js";

import { ActionBase } from "./models.js";

export type RichMenuSwitchAction = ActionBase & {
  type: "richmenuswitch";

  /**
   * @minLength 0
   * @maxLength 300
   */
  data?: string;
  /**
   * @minLength 0
   * @maxLength 32
   */
  richMenuAliasId?: string;
};
