/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RichMenuBatchLinkOperation } from "./models.js";
import { RichMenuBatchUnlinkOperation } from "./models.js";
import { RichMenuBatchUnlinkAllOperation } from "./models.js";

/**
 * Rich menu operation object represents the batch operation to the rich menu linked to the user.
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#batch-control-rich-menus-of-users-operations">https://developers.line.biz/en/reference/messaging-api/#batch-control-rich-menus-of-users-operations</a>
 */
export type RichMenuBatchOperation =
  | RichMenuBatchLinkOperation // link
  | RichMenuBatchUnlinkOperation // unlink
  | RichMenuBatchUnlinkAllOperation; // unlinkAll

export type RichMenuBatchOperationBase = {
  /**
   * The type of operation to the rich menu linked to the user. One of link, unlink, or unlinkAll.
   */
  type: string;
};
