/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';
import { RichMenuAliasResponse } from './richMenuAliasResponse';

export class RichMenuAliasListResponse {
    /**
    * Rich menu aliases.
    */
    'aliases': Array<RichMenuAliasResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aliases",
            "baseName": "aliases",
            "type": "Array<RichMenuAliasResponse>"
        }    ];

    static getAttributeTypeMap() {
        return RichMenuAliasListResponse.attributeTypeMap;
    }
}

