/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RichMenuBatchOperation } from "./richMenuBatchOperation.js";

export type RichMenuBatchRequest = {
  /**
   * Array of Rich menu operation object...
   */
  operations: Array<RichMenuBatchOperation> /**/;
  /**
   * Key for retry. Key value is a string matching the regular expression pattern
   */
  resumeRequestKey?: string /**/;
};
