/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Message } from "./message.js";
import { QuickReply } from "./quickReply.js";
import { Sender } from "./sender.js";

import { MessageBase } from "./models.js";

export type StickerMessage = MessageBase & {
  type: "sticker";
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#sticker-message">packageId Documentation</a>
   */
  packageId: string /**/;
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#sticker-message">stickerId Documentation</a>
   */
  stickerId: string /**/;
  /**
   * Quote token of the message you want to quote.
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#sticker-message">quoteToken Documentation</a>
   */
  quoteToken?: string /**/;
};
