/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EmojiSubstitutionObject } from "./models.js";
import { MentionSubstitutionObject } from "./models.js";

export type SubstitutionObject =
  | EmojiSubstitutionObject // emoji
  | MentionSubstitutionObject; // mention

/**
 * An object that defines the replacement value for a placeholder in the text.
 */
export type SubstitutionObjectBase = {
  /**
   * Type of substitution object
   */
  type: string /**/;
};
