/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum SubscriptionPeriodDemographic {
    _7 = <any> 'day_7',
    _30 = <any> 'day_30',
    _90 = <any> 'day_90',
    _180 = <any> 'day_180',
    _365 = <any> 'day_365'
}
