/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Emoji } from "./emoji.js";
import { Message } from "./message.js";
import { QuickReply } from "./quickReply.js";
import { Sender } from "./sender.js";

import { MessageBase } from "./models.js";

export type TextMessage = MessageBase & {
  type: "text";
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#text-message">text Documentation</a>
   */
  text: string /**/;
  /**
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#text-message">emojis Documentation</a>
   */
  emojis?: Array<Emoji> /**/;
  /**
   * Quote token of the message you want to quote.
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#text-message">quoteToken Documentation</a>
   */
  quoteToken?: string /**/;
};
