/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-locals */
import { GetFriendsDemographicsResponse } from "../model/getFriendsDemographicsResponse";
import { GetMessageEventResponse } from "../model/getMessageEventResponse";
import { GetNumberOfFollowersResponse } from "../model/getNumberOfFollowersResponse";
import { GetNumberOfMessageDeliveriesResponse } from "../model/getNumberOfMessageDeliveriesResponse";
import { GetStatisticsPerUnitResponse } from "../model/getStatisticsPerUnitResponse";

import * as Types from "../../types";
import { ensureJSON } from "../../utils";
import { Readable } from "stream";

import HTTPClient from "../../http";

const pkg = require("../../../package.json");

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

interface httpClientConfig {
  baseURL?: string;
  channelAccessToken: string;
  // TODO support defaultHeaders?
}

export class InsightClient {
  private config: httpClientConfig;

  constructor(config: httpClientConfig) {
    this.config = {
      baseURL: "https://api.line.me",
      ...config,
    };
  }

  /**
   * Retrieves the demographic attributes for a LINE Official Account\'s friends.You can only retrieve information about friends for LINE Official Accounts created by users in Japan (JP), Thailand (TH), Taiwan (TW) and Indonesia (ID).
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-demographic"> Documentation</a>
   */
  public async getFriendsDemographics(): Promise<GetFriendsDemographicsResponse> {
    const requestUrl = new URL(
      "/v2/bot/insight/demographic",
      this.config.baseURL,
    );

    const resp = await fetch(requestUrl, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },
    });

    const resBody = await resp.json();

    // for backward compatibility, inject x-line-request-id to response body.
    const { LINE_REQUEST_ID_HTTP_HEADER_NAME } = Types;
    const requestIdHeader = resp.headers.get(LINE_REQUEST_ID_HTTP_HEADER_NAME);
    if (requestIdHeader) {
      resBody[LINE_REQUEST_ID_HTTP_HEADER_NAME] = requestIdHeader;
    }

    return resBody;
  }
  /**
   * Returns statistics about how users interact with narrowcast messages or broadcast messages sent from your LINE Official Account.
   * @summary Get user interaction statistics
   * @param requestId Request ID of a narrowcast message or broadcast message. Each Messaging API request has a request ID.
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-message-event">Get user interaction statistics Documentation</a>
   */
  public async getMessageEvent(
    requestId: string,
  ): Promise<GetMessageEventResponse> {
    const requestUrl = new URL(
      "/v2/bot/insight/message/event",
      this.config.baseURL,
    );

    const queryParams = new URLSearchParams();
    queryParams.append("requestId", String(requestId));

    requestUrl.search = queryParams.toString();

    const resp = await fetch(requestUrl, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },
    });

    const resBody = await resp.json();

    // for backward compatibility, inject x-line-request-id to response body.
    const { LINE_REQUEST_ID_HTTP_HEADER_NAME } = Types;
    const requestIdHeader = resp.headers.get(LINE_REQUEST_ID_HTTP_HEADER_NAME);
    if (requestIdHeader) {
      resBody[LINE_REQUEST_ID_HTTP_HEADER_NAME] = requestIdHeader;
    }

    return resBody;
  }
  /**
   * Returns the number of users who have added the LINE Official Account on or before a specified date.
   * @summary Get number of followers
   * @param date Date for which to retrieve the number of followers.  Format: yyyyMMdd (e.g. 20191231) Timezone: UTC+9
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-number-of-followers">Get number of followers Documentation</a>
   */
  public async getNumberOfFollowers(
    date?: string,
  ): Promise<GetNumberOfFollowersResponse> {
    const requestUrl = new URL(
      "/v2/bot/insight/followers",
      this.config.baseURL,
    );

    const queryParams = new URLSearchParams();
    queryParams.append("date", String(date));

    requestUrl.search = queryParams.toString();

    const resp = await fetch(requestUrl, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },
    });

    const resBody = await resp.json();

    // for backward compatibility, inject x-line-request-id to response body.
    const { LINE_REQUEST_ID_HTTP_HEADER_NAME } = Types;
    const requestIdHeader = resp.headers.get(LINE_REQUEST_ID_HTTP_HEADER_NAME);
    if (requestIdHeader) {
      resBody[LINE_REQUEST_ID_HTTP_HEADER_NAME] = requestIdHeader;
    }

    return resBody;
  }
  /**
   * Returns the number of messages sent from LINE Official Account on a specified day.
   * @summary Get number of message deliveries
   * @param date Date for which to retrieve number of sent messages. - Format: yyyyMMdd (e.g. 20191231) - Timezone: UTC+9
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-number-of-delivery-messages">Get number of message deliveries Documentation</a>
   */
  public async getNumberOfMessageDeliveries(
    date: string,
  ): Promise<GetNumberOfMessageDeliveriesResponse> {
    const requestUrl = new URL(
      "/v2/bot/insight/message/delivery",
      this.config.baseURL,
    );

    const queryParams = new URLSearchParams();
    queryParams.append("date", String(date));

    requestUrl.search = queryParams.toString();

    const resp = await fetch(requestUrl, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },
    });

    const resBody = await resp.json();

    // for backward compatibility, inject x-line-request-id to response body.
    const { LINE_REQUEST_ID_HTTP_HEADER_NAME } = Types;
    const requestIdHeader = resp.headers.get(LINE_REQUEST_ID_HTTP_HEADER_NAME);
    if (requestIdHeader) {
      resBody[LINE_REQUEST_ID_HTTP_HEADER_NAME] = requestIdHeader;
    }

    return resBody;
  }
  /**
   * You can check the per-unit statistics of how users interact with push messages and multicast messages sent from your LINE Official Account.
   * @param customAggregationUnit Name of aggregation unit specified when sending the message. Case-sensitive. For example, `Promotion_a` and `Promotion_A` are regarded as different unit names.
   * @param from Start date of aggregation period.  Format: yyyyMMdd (e.g. 20210301) Time zone: UTC+9
   * @param to End date of aggregation period. The end date can be specified for up to 30 days later. For example, if the start date is 20210301, the latest end date is 20210331.  Format: yyyyMMdd (e.g. 20210301) Time zone: UTC+9
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-statistics-per-unit"> Documentation</a>
   */
  public async getStatisticsPerUnit(
    customAggregationUnit: string,
    from: string,
    to: string,
  ): Promise<GetStatisticsPerUnitResponse> {
    const requestUrl = new URL(
      "/v2/bot/insight/message/event/aggregation",
      this.config.baseURL,
    );

    const queryParams = new URLSearchParams();
    queryParams.append("customAggregationUnit", String(customAggregationUnit));
    queryParams.append("from", String(from));
    queryParams.append("to", String(to));

    requestUrl.search = queryParams.toString();

    const resp = await fetch(requestUrl, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },
    });

    const resBody = await resp.json();

    // for backward compatibility, inject x-line-request-id to response body.
    const { LINE_REQUEST_ID_HTTP_HEADER_NAME } = Types;
    const requestIdHeader = resp.headers.get(LINE_REQUEST_ID_HTTP_HEADER_NAME);
    if (requestIdHeader) {
      resBody[LINE_REQUEST_ID_HTTP_HEADER_NAME] = requestIdHeader;
    }

    return resBody;
  }
}
