/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-locals */
import { AttachModuleResponse } from "../model/attachModuleResponse";

import * as Types from "../../types";
import { ensureJSON } from "../../utils";
import { Readable } from "stream";

import HTTPClient from "../../http";

const pkg = require("../../../package.json");

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

interface httpClientConfig {
  baseURL?: string;
  channelAccessToken: string;
  // TODO support defaultHeaders?
}

export class LineModuleAttachClient {
  private config: httpClientConfig;

  constructor(config: httpClientConfig) {
    this.config = {
      baseURL: "https://manager.line.biz",
      ...config,
    };
  }

  /**
   * Attach by operation of the module channel provider
   * @param grantType authorization_code
   * @param code Authorization code received from the LINE Platform.
   * @param redirectUri Specify the redirect_uri specified in the URL for authentication and authorization.
   * @param codeVerifier Specify when using PKCE (Proof Key for Code Exchange) defined in the OAuth 2.0 extension specification as a countermeasure against authorization code interception attacks.
   * @param clientId Instead of using Authorization header, you can use this parameter to specify the channel ID of the module channel. You can find the channel ID of the module channel in the LINE Developers Console.
   * @param clientSecret Instead of using Authorization header, you can use this parameter to specify the channel secret of the module channel. You can find the channel secret of the module channel in the LINE Developers Console.
   * @param region If you specified a value for region in the URL for authentication and authorization, specify the same value.
   * @param basicSearchId If you specified a value for basic_search_id in the URL for authentication and authorization, specify the same value.
   * @param scope If you specified a value for scope in the URL for authentication and authorization, specify the same value.
   * @param brandType If you specified a value for brand_type in the URL for authentication and authorization, specify the same value.
   *
   * @see <a href="https://developers.line.biz/en/reference/partner-docs/#link-attach-by-operation-module-channel-provider"> Documentation</a>
   */
  public async attachModule(
    grantType?: string,
    code?: string,
    redirectUri?: string,
    codeVerifier?: string,
    clientId?: string,
    clientSecret?: string,
    region?: string,
    basicSearchId?: string,
    scope?: string,
    brandType?: string,
  ): Promise<AttachModuleResponse> {
    const requestUrl = new URL("/module/auth/v1/token", this.config.baseURL);

    const formData = new URLSearchParams();
    formData.append("grantType", String(grantType));
    formData.append("code", String(code));
    formData.append("redirectUri", String(redirectUri));
    formData.append("codeVerifier", String(codeVerifier));
    formData.append("clientId", String(clientId));
    formData.append("clientSecret", String(clientSecret));
    formData.append("region", String(region));
    formData.append("basicSearchId", String(basicSearchId));
    formData.append("scope", String(scope));
    formData.append("brandType", String(brandType));

    const resp = await fetch(requestUrl, {
      method: "POST",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,

        "Content-type": "application/x-www-form-urlencoded",
      },

      body: formData,
    });

    const resBody = await resp.json();

    // for backward compatibility, inject x-line-request-id to response body.
    const { LINE_REQUEST_ID_HTTP_HEADER_NAME } = Types;
    const requestIdHeader = resp.headers.get(LINE_REQUEST_ID_HTTP_HEADER_NAME);
    if (requestIdHeader) {
      resBody[LINE_REQUEST_ID_HTTP_HEADER_NAME] = requestIdHeader;
    }

    return resBody;
  }
}
