/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Mentionee } from "./mentionee.js";

/**
 * Mentioned target is entire group
 */
import { MentioneeBase } from "./models.js";

export type AllMentionee = MentioneeBase & {
  type: "all";
};
