/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModuleContent } from "./moduleContent.js";

import { ModuleContentBase } from "./models.js";

export type AttachedModuleContent = ModuleContentBase & {
  type: "attached";
  /**
   * User ID of the bot on the attached LINE Official Account
   */
  botId: string /**/;
  /**
   * An array of strings indicating the scope permitted by the admin of the LINE Official Account.
   */
  scopes: Array<string> /**/;
};
