/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type BeaconContent = {
  /**
   * Hardware ID of the beacon that was detected
   */
  hwid: string /**/;
  /**
   * Type of beacon event.
   */
  type: BeaconContent.TypeEnum /**/;
  /**
   * Device message of beacon that was detected.
   */
  dm?: string /**/;
};

export namespace BeaconContent {
  export type TypeEnum = "enter" | "banner" | "stay";
}
