/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Emoji = {
  /**
   * Index position for a character in text, with the first character being at position 0.
   */
  index: number /**/;
  /**
   * The length of the LINE emoji string. For LINE emoji (hello), 7 is the length.
   */
  length: number /**/;
  /**
   * Product ID for a LINE emoji set.
   */
  productId: string /**/;
  /**
   * ID for a LINE emoji inside a set.
   */
  emojiId: string /**/;
};
