/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type ImageSet = {
  /**
   * Image set ID. Only included when multiple images are sent simultaneously.
   */
  id: string /**/;
  /**
   * An index starting from 1, indicating the image number in a set of images sent simultaneously. Only included when multiple images are sent simultaneously. However, it won\'t be included if the sender is using LINE 11.15 or earlier for Android.
   */
  index?: number /**/;
  /**
   * The total number of images sent simultaneously.
   */
  total?: number /**/;
};
