/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MembershipContent } from "./membershipContent.js";

import { MembershipContentBase } from "./models.js";

export type LeftMembershipContent = MembershipContentBase & {
  type: "left";
  /**
   * The ID of the membership that the user left. This is defined for each membership.
   */
  membershipId: number /**/;
};
