/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeliveryContext } from "./deliveryContext.js";
import { Event } from "./event.js";
import { EventMode } from "./eventMode.js";
import { MembershipContent } from "./membershipContent.js";
import { Source } from "./source.js";

/**
 * This event indicates that a user has subscribed (joined), unsubscribed (left), or renewed the bot\'s membership.
 */
import { EventBase } from "./models.js";

export type MembershipEvent = EventBase & {
  type: "membership";
  /**
   * Reply token used to send reply message to this event
   */
  replyToken: string /**/;
  /**
   */
  membership: MembershipContent /**/;
};

export namespace MembershipEvent {}
