/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeliveryContext } from "./deliveryContext.js";
import { Event } from "./event.js";
import { EventMode } from "./eventMode.js";
import { MessageContent } from "./messageContent.js";
import { Source } from "./source.js";

/**
 * Webhook event object which contains the sent message.
 */
import { EventBase } from "./models.js";

export type MessageEvent = EventBase & {
  type: "message";
  /**
   */
  replyToken?: string /**/;
  /**
   */
  message: MessageContent /**/;
};

export namespace MessageEvent {}
