/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageContent } from './messageContent';


import { MessageContentBase } from './models';
export type StickerMessageContent = MessageContentBase &  { 
    type: "sticker",
    /**
    * Message ID
    */
    'id': string/**/;
    /**
    * Package ID
    */
    'packageId': string/**/;
    /**
    * Sticker ID
    */
    'stickerId': string/**/;
    /**
    */
    'stickerResourceType': StickerMessageContent.StickerResourceTypeEnum/**/;
    /**
    * Array of up to 15 keywords describing the sticker. If a sticker has 16 or more keywords, a random selection of 15 keywords will be returned. The keyword selection is random for each event, so different keywords may be returned for the same sticker. 
    */
    'keywords'?: Array<string>/**/;
    /**
    * Any text entered by the user. This property is only included for message stickers. Max character limit: 100 
    */
    'text'?: string/**/;
    /**
    * Quote token to quote this message. 
    */
    'quoteToken': string/**/;
    /**
    * Message ID of a quoted message. Only included when the received message quotes a past message.  
    */
    'quotedMessageId'?: string/**/;
}

export namespace StickerMessageContent {
    export type StickerResourceTypeEnum = 
            | 'STATIC'
            | 'ANIMATION'
            | 'SOUND'
            | 'ANIMATION_SOUND'
            | 'POPUP'
            | 'POPUP_SOUND'
            | 'CUSTOM'
            | 'MESSAGE'
            | 'NAME_TEXT'
            'PER_STICKER_TEXT'
    ;
}
