/**
 * Channel Access Token API
 * This document describes Channel Access Token API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Issued stateless channel access token
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#issue-stateless-channel-access-token">https://developers.line.biz/en/reference/messaging-api/#issue-stateless-channel-access-token</a>
 */
export type IssueStatelessChannelAccessTokenResponse = {
  /**
   * A stateless channel access token. The token is an opaque string which means its format is an implementation detail and the consumer of this token should never try to use the data parsed from the token.
   */
  access_token: string;
  /**
   * Duration in seconds after which the issued access token expires
   */
  expires_in: number;
  /**
   * Token type. The value is always `Bearer`.
   * @default 'Bearer'
   */
  token_type: string;
};
