/**
 * Channel Access Token API
 * This document describes Channel Access Token API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Issued channel access token
*/
export class IssueChannelAccessTokenResponse {
    /**
    * Channel access token. 
    */
    'accessToken': string;
    /**
    * Amount of time in seconds from issue to expiration of the channel access token
    */
    'expiresIn': number;
    /**
    * A token type.
    */
    'tokenType': string = 'Bearer';
    /**
    * Unique key ID for identifying the channel access token.
    */
    'keyId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string"
        },
        {
            "name": "expiresIn",
            "baseName": "expires_in",
            "type": "number"
        },
        {
            "name": "tokenType",
            "baseName": "token_type",
            "type": "string"
        },
        {
            "name": "keyId",
            "baseName": "key_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssueChannelAccessTokenResponse.attributeTypeMap;
    }
}

