/**
 * Channel Access Token API
 * This document describes Channel Access Token API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Verification result
 */
export type VerifyChannelAccessTokenResponse = {
  /**
   * The channel ID for which the channel access token was issued.
   */
  clientId: string /**/;
  /**
   * Number of seconds before the channel access token expires.
   */
  expiresIn: number /**/;
  /**
   * Permissions granted to the channel access token.
   */
  scope?: string /**/;
};
