/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';

export class AppTypeTile {
    /**
    * users\' OS
    */
    'appType'?: AppTypeTile.AppTypeEnum;
    /**
    * Percentage
    */
    'percentage'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appType",
            "baseName": "appType",
            "type": "AppTypeTile.AppTypeEnum"
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AppTypeTile.attributeTypeMap;
    }
}

export namespace AppTypeTile {
    export enum AppTypeEnum {
        Ios = <any> 'ios',
        Android = <any> 'android',
        Others = <any> 'others'
    }
}
