/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type AreaTile = {
  /**
   * users\' country and region
   */
  area?: string /**/;
  /**
   * Percentage
   */
  percentage?: number /**/;
};
