/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgeTile } from "./ageTile.js";
import { AppTypeTile } from "./appTypeTile.js";
import { AreaTile } from "./areaTile.js";
import { GenderTile } from "./genderTile.js";
import { SubscriptionPeriodTile } from "./subscriptionPeriodTile.js";

/**
 * Get friend demographics
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-demographic">https://developers.line.biz/en/reference/messaging-api/#get-demographic</a>
 */
export type GetFriendsDemographicsResponse = {
  /**
   * true if friend demographic information is available.
   */
  available?: boolean;
  /**
   * Percentage per gender.
   */
  genders?: Array<GenderTile>;
  /**
   * Percentage per age group.
   */
  ages?: Array<AgeTile>;
  /**
   * Percentage per area.
   */
  areas?: Array<AreaTile>;
  /**
   * Percentage by OS.
   */
  appTypes?: Array<AppTypeTile>;
  /**
   * Percentage per friendship duration.
   */
  subscriptionPeriods?: Array<SubscriptionPeriodTile>;
};
