/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';

/**
* Get number of message deliveries
*/
export class GetNumberOfMessageDeliveriesResponse {
    /**
    * Status of the counting process.
    */
    'status'?: GetNumberOfMessageDeliveriesResponse.StatusEnum;
    /**
    * Number of messages sent to all of this LINE Official Account\'s friends (broadcast messages).
    */
    'broadcast'?: number;
    /**
    * Number of messages sent to some of this LINE Official Account\'s friends, based on specific attributes (targeted messages).
    */
    'targeting'?: number;
    /**
    * Number of auto-response messages sent.
    */
    'autoResponse'?: number;
    /**
    * Number of greeting messages sent.
    */
    'welcomeResponse'?: number;
    /**
    * Number of messages sent from LINE Official Account Manager [Chat screen](https://www.linebiz.com/jp/manual/OfficialAccountManager/chats/) (only available in Japanese).
    */
    'chat'?: number;
    /**
    * Number of broadcast messages sent with the `Send broadcast message` Messaging API operation.
    */
    'apiBroadcast'?: number;
    /**
    * Number of push messages sent with the `Send push message` Messaging API operation.
    */
    'apiPush'?: number;
    /**
    * Number of multicast messages sent with the `Send multicast message` Messaging API operation.
    */
    'apiMulticast'?: number;
    /**
    * Number of narrowcast messages sent with the `Send narrowcast message` Messaging API operation.
    */
    'apiNarrowcast'?: number;
    /**
    * Number of replies sent with the `Send reply message` Messaging API operation.
    */
    'apiReply'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "GetNumberOfMessageDeliveriesResponse.StatusEnum"
        },
        {
            "name": "broadcast",
            "baseName": "broadcast",
            "type": "number"
        },
        {
            "name": "targeting",
            "baseName": "targeting",
            "type": "number"
        },
        {
            "name": "autoResponse",
            "baseName": "autoResponse",
            "type": "number"
        },
        {
            "name": "welcomeResponse",
            "baseName": "welcomeResponse",
            "type": "number"
        },
        {
            "name": "chat",
            "baseName": "chat",
            "type": "number"
        },
        {
            "name": "apiBroadcast",
            "baseName": "apiBroadcast",
            "type": "number"
        },
        {
            "name": "apiPush",
            "baseName": "apiPush",
            "type": "number"
        },
        {
            "name": "apiMulticast",
            "baseName": "apiMulticast",
            "type": "number"
        },
        {
            "name": "apiNarrowcast",
            "baseName": "apiNarrowcast",
            "type": "number"
        },
        {
            "name": "apiReply",
            "baseName": "apiReply",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetNumberOfMessageDeliveriesResponse.attributeTypeMap;
    }
}

export namespace GetNumberOfMessageDeliveriesResponse {
    export enum StatusEnum {
        Ready = <any> 'ready',
        Unready = <any> 'unready',
        OutOfService = <any> 'out_of_service'
    }
}
