/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetRichMenuInsightDailyResponseDailyMetrics } from "./getRichMenuInsightDailyResponseDailyMetrics.js";

/**
 * Daily impression metrics for the whole rich menu.
 */
export type GetRichMenuInsightDailyResponseImpression = {
  /**
   * Per-day impression metrics.
   */
  metrics: Array<GetRichMenuInsightDailyResponseDailyMetrics>;
};
