/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Aggregated number of events and unique users for a single day.
 */
export type GetRichMenuInsightDailyResponseDailyMetrics = {
  /**
   * The date (JST) of these metrics. Format: yyyyMMdd (e.g. 20260213).
   * Pattern: /^[0-9]{8}$/
   */
  date: string;
  /**
   * Number of impressions or clicks on this day.
   */
  count: number;
  /**
   * Approximate number of unique users who triggered an impression or click on this day.
   */
  uniqueUsers: number;
};
