/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Statistics related to messages.
*/
export class GetStatisticsPerUnitResponseOverview {
    /**
    * Number of users who opened the message, meaning they displayed at least 1 bubble.
    */
    'uniqueImpression'?: number | null;
    /**
    * Number of users who opened any URL in the message.
    */
    'uniqueClick'?: number | null;
    /**
    * Number of users who started playing any video or audio in the message.
    */
    'uniqueMediaPlayed'?: number | null;
    /**
    * Number of users who played the entirety of any video or audio in the message.
    */
    'uniqueMediaPlayed100Percent'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uniqueImpression",
            "baseName": "uniqueImpression",
            "type": "number"
        },
        {
            "name": "uniqueClick",
            "baseName": "uniqueClick",
            "type": "number"
        },
        {
            "name": "uniqueMediaPlayed",
            "baseName": "uniqueMediaPlayed",
            "type": "number"
        },
        {
            "name": "uniqueMediaPlayed100Percent",
            "baseName": "uniqueMediaPlayed100Percent",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetStatisticsPerUnitResponseOverview.attributeTypeMap;
    }
}

