/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetStatisticsPerUnitResponseClick } from "./getStatisticsPerUnitResponseClick.js";
import { GetStatisticsPerUnitResponseMessage } from "./getStatisticsPerUnitResponseMessage.js";
import { GetStatisticsPerUnitResponseOverview } from "./getStatisticsPerUnitResponseOverview.js";

/**
 * Response object for `get statistics per unit`
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-statistics-per-unit-response">https://developers.line.biz/en/reference/messaging-api/#get-statistics-per-unit-response</a>
 */
export type GetStatisticsPerUnitResponse = {
  overview: GetStatisticsPerUnitResponseOverview;
  /**
   * Array of information about individual message bubbles.
   */
  messages: Array<GetStatisticsPerUnitResponseMessage>;
  /**
   * Array of information about opened URLs in the message.
   */
  clicks: Array<GetStatisticsPerUnitResponseClick>;
};
