import { Readable } from "node:stream";
import HTTPClient from "./http-axios.js";
import * as Types from "./types.js";
import { AxiosRequestConfig, AxiosResponse } from "axios";
import { createMultipartFormData, ensureJSON, toArray } from "./utils.js";
import {
  DATA_API_PREFIX,
  MESSAGING_API_PREFIX,
  OAUTH_BASE_PREFIX,
  OAUTH_BASE_PREFIX_V2_1,
} from "./endpoints.js";

type ChatType = "group" | "room";
type RequestOption = {
  retryKey: string;
};

/**
 * @deprecated Use clients generated by openapi spec instead.
 */
export default class Client {
  public config: Types.ClientConfig;
  private http: HTTPClient;

  private requestOption: Partial<RequestOption> = {};

  constructor(config: Types.ClientConfig) {
    if (!config.channelAccessToken) {
      throw new Error("no channel access token");
    }

    this.config = config;
    this.http = new HTTPClient({
      defaultHeaders: {
        Authorization: "Bearer " + this.config.channelAccessToken,
      },
      responseParser: this.parseHTTPResponse.bind(this),
      ...config.httpConfig,
    });
  }

  /**
   * @deprecated No direct equivalent in LineBotClient. Pass `xLineRetryKey` as the 2nd argument to `pushMessage`, `multicast`, `narrowcast`, or `broadcast` directly.
   */
  public setRequestOptionOnce(option: Partial<RequestOption>) {
    this.requestOption = option;
  }

  private generateRequestConfig(): Partial<AxiosRequestConfig> {
    const config: Partial<AxiosRequestConfig> = { headers: {} };
    if (this.requestOption.retryKey) {
      config.headers["X-Line-Retry-Key"] = this.requestOption.retryKey;
    }

    // clear requestOption
    this.requestOption = {};
    return config;
  }

  private parseHTTPResponse(response: AxiosResponse) {
    const { LINE_REQUEST_ID_HTTP_HEADER_NAME } = Types;
    let resBody = {
      ...response.data,
    };
    if (response.headers[LINE_REQUEST_ID_HTTP_HEADER_NAME]) {
      resBody[LINE_REQUEST_ID_HTTP_HEADER_NAME] =
        response.headers[LINE_REQUEST_ID_HTTP_HEADER_NAME];
    }
    return resBody;
  }

  /**
   * @deprecated Use {@link LineBotClient.pushMessage} instead.
   * @example
   * // Before:
   * client.pushMessage(to, messages, notificationDisabled, customAggregationUnits);
   * // After:
   * lineBotClient.pushMessage({ to, messages, notificationDisabled, customAggregationUnits }, xLineRetryKey);
   */
  public pushMessage(
    to: string,
    messages: Types.Message | Types.Message[],
    notificationDisabled: boolean = false,
    customAggregationUnits?: string[],
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/message/push`,
      {
        messages: toArray(messages),
        to,
        notificationDisabled,
        customAggregationUnits,
      },
      this.generateRequestConfig(),
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.replyMessage} instead.
   * @example
   * // Before:
   * client.replyMessage(replyToken, messages, notificationDisabled);
   * // After:
   * lineBotClient.replyMessage({ replyToken, messages, notificationDisabled });
   */
  public replyMessage(
    replyToken: string,
    messages: Types.Message | Types.Message[],
    notificationDisabled: boolean = false,
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(`${MESSAGING_API_PREFIX}/message/reply`, {
      messages: toArray(messages),
      replyToken,
      notificationDisabled,
    });
  }

  /**
   * @deprecated Use {@link LineBotClient.multicast} instead.
   * @example
   * // Before:
   * client.multicast(to, messages, notificationDisabled, customAggregationUnits);
   * // After:
   * lineBotClient.multicast({ to, messages, notificationDisabled, customAggregationUnits }, xLineRetryKey);
   */
  public async multicast(
    to: string[],
    messages: Types.Message | Types.Message[],
    notificationDisabled: boolean = false,
    customAggregationUnits?: string[],
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/message/multicast`,
      {
        messages: toArray(messages),
        to,
        notificationDisabled,
        customAggregationUnits,
      },
      this.generateRequestConfig(),
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.narrowcast} instead.
   * @example
   * // Before:
   * client.narrowcast(messages, recipient, filter, limit, notificationDisabled);
   * // After:
   * lineBotClient.narrowcast({ messages, recipient, filter, limit, notificationDisabled }, xLineRetryKey);
   */
  public async narrowcast(
    messages: Types.Message | Types.Message[],
    recipient?: Types.ReceieptObject,
    filter?: { demographic: Types.DemographicFilterObject },
    limit?: { max?: number; upToRemainingQuota?: boolean },
    notificationDisabled?: boolean,
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/message/narrowcast`,
      {
        messages: toArray(messages),
        recipient,
        filter,
        limit,
        notificationDisabled,
      },
      this.generateRequestConfig(),
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.broadcast} instead.
   * @example
   * // Before:
   * client.broadcast(messages, notificationDisabled);
   * // After:
   * lineBotClient.broadcast({ messages, notificationDisabled }, xLineRetryKey);
   */
  public async broadcast(
    messages: Types.Message | Types.Message[],
    notificationDisabled: boolean = false,
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/message/broadcast`,
      {
        messages: toArray(messages),
        notificationDisabled,
      },
      this.generateRequestConfig(),
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.validatePush} instead.
   * @example
   * // Before:
   * client.validatePushMessageObjects(messages);
   * // After:
   * lineBotClient.validatePush({ messages });
   */
  public validatePushMessageObjects(
    messages: Types.Message | Types.Message[],
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/message/validate/push`,
      {
        messages: toArray(messages),
      },
      this.generateRequestConfig(),
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.validateReply} instead.
   * @example
   * // Before:
   * client.validateReplyMessageObjects(messages);
   * // After:
   * lineBotClient.validateReply({ messages });
   */
  public validateReplyMessageObjects(
    messages: Types.Message | Types.Message[],
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(`${MESSAGING_API_PREFIX}/message/validate/reply`, {
      messages: toArray(messages),
    });
  }

  /**
   * @deprecated Use {@link LineBotClient.validateMulticast} instead.
   * @example
   * // Before:
   * client.validateMulticastMessageObjects(messages);
   * // After:
   * lineBotClient.validateMulticast({ messages });
   */
  public async validateMulticastMessageObjects(
    messages: Types.Message | Types.Message[],
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/message/validate/multicast`,
      {
        messages: toArray(messages),
      },
      this.generateRequestConfig(),
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.validateNarrowcast} instead.
   * @example
   * // Before:
   * client.validateNarrowcastMessageObjects(messages);
   * // After:
   * lineBotClient.validateNarrowcast({ messages });
   */
  public async validateNarrowcastMessageObjects(
    messages: Types.Message | Types.Message[],
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/message/validate/narrowcast`,
      {
        messages: toArray(messages),
      },
      this.generateRequestConfig(),
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.validateBroadcast} instead.
   * @example
   * // Before:
   * client.validateBroadcastMessageObjects(messages);
   * // After:
   * lineBotClient.validateBroadcast({ messages });
   */
  public async validateBroadcastMessageObjects(
    messages: Types.Message | Types.Message[],
  ): Promise<Types.MessageAPIResponseBase> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/message/validate/broadcast`,
      {
        messages: toArray(messages),
      },
      this.generateRequestConfig(),
    );
  }

  /**
   * @deprecated No direct equivalent in LineBotClient. See docs/guide/migration.md for details.
   */
  public validateCustomAggregationUnits(units: string[]): {
    messages: string[];
    valid: boolean;
  } {
    const messages: string[] = [];
    if (units.length > 1) {
      messages.push("customAggregationUnits can only contain one unit");
    }
    units.forEach((unit, index) => {
      if (unit.length > 30) {
        messages.push(
          `customAggregationUnits[${index}] must be less than or equal to 30 characters`,
        );
      }
      if (!/^[a-zA-Z0-9_]+$/.test(unit)) {
        messages.push(
          `customAggregationUnits[${index}] must be alphanumeric characters or underscores`,
        );
      }
    });

    return {
      messages,
      valid: messages.length === 0,
    };
  }

  /**
   * @deprecated Use {@link LineBotClient.getProfile} instead.
   * @example
   * // Before:
   * client.getProfile(userId);
   * // After:
   * lineBotClient.getProfile(userId);
   */
  public async getProfile(userId: string): Promise<Types.Profile> {
    const profile = await this.http.get<Types.Profile>(
      `${MESSAGING_API_PREFIX}/profile/${userId}`,
    );
    return ensureJSON(profile);
  }

  private async getChatMemberProfile(
    chatType: ChatType,
    chatId: string,
    userId: string,
  ): Promise<Types.Profile> {
    const profile = await this.http.get<Types.Profile>(
      `${MESSAGING_API_PREFIX}/${chatType}/${chatId}/member/${userId}`,
    );
    return ensureJSON(profile);
  }

  /**
   * @deprecated Use {@link LineBotClient.getGroupMemberProfile} instead.
   * @example
   * // Before:
   * client.getGroupMemberProfile(groupId, userId);
   * // After:
   * lineBotClient.getGroupMemberProfile(groupId, userId);
   */
  public async getGroupMemberProfile(
    groupId: string,
    userId: string,
  ): Promise<Types.Profile> {
    return this.getChatMemberProfile("group", groupId, userId);
  }

  /**
   * @deprecated Use {@link LineBotClient.getRoomMemberProfile} instead.
   * @example
   * // Before:
   * client.getRoomMemberProfile(roomId, userId);
   * // After:
   * lineBotClient.getRoomMemberProfile(roomId, userId);
   */
  public async getRoomMemberProfile(
    roomId: string,
    userId: string,
  ): Promise<Types.Profile> {
    return this.getChatMemberProfile("room", roomId, userId);
  }

  private async getChatMemberIds(
    chatType: ChatType,
    chatId: string,
  ): Promise<string[]> {
    let memberIds: string[] = [];

    let start: string;
    do {
      const res = await this.http.get<{ memberIds: string[]; next?: string }>(
        `${MESSAGING_API_PREFIX}/${chatType}/${chatId}/members/ids`,
        start ? { start } : null,
      );
      ensureJSON(res);
      memberIds = memberIds.concat(res.memberIds);
      start = res.next;
    } while (start);

    return memberIds;
  }

  /**
   * @deprecated Use {@link LineBotClient.getGroupMembersIds} instead. Note: the new method does not auto-paginate.
   * @example
   * // Before:
   * client.getGroupMemberIds(groupId);
   * // After:
   * lineBotClient.getGroupMembersIds(groupId);
   */
  public async getGroupMemberIds(groupId: string): Promise<string[]> {
    return this.getChatMemberIds("group", groupId);
  }

  /**
   * @deprecated Use {@link LineBotClient.getRoomMembersIds} instead. Note: the new method does not auto-paginate.
   * @example
   * // Before:
   * client.getRoomMemberIds(roomId);
   * // After:
   * lineBotClient.getRoomMembersIds(roomId);
   */
  public async getRoomMemberIds(roomId: string): Promise<string[]> {
    return this.getChatMemberIds("room", roomId);
  }

  /**
   * @deprecated Use {@link LineBotClient.getFollowers} instead. Note: the new method does not auto-paginate.
   * The old method collected all pages and returned a flat `string[]`.
   * The new method returns a single page (`GetFollowersResponse`); call it in a loop using the `next` token to retrieve all followers.
   * @example
   * // Before:
   * const allIds = await client.getBotFollowersIds();
   * // After (manual pagination):
   * let next: string | undefined;
   * const allIds: string[] = [];
   * do {
   *   const res = await lineBotClient.getFollowers(next);
   *   allIds.push(...res.userIds);
   *   next = res.next;
   * } while (next);
   */
  public async getBotFollowersIds(): Promise<string[]> {
    let userIds: string[] = [];

    let start: string;
    do {
      const res = await this.http.get<{ userIds: string[]; next?: string }>(
        `${MESSAGING_API_PREFIX}/followers/ids`,
        start ? { start, limit: 1000 } : { limit: 1000 },
      );
      ensureJSON(res);
      userIds = userIds.concat(res.userIds);
      start = res.next;
    } while (start);

    return userIds;
  }

  /**
   * @deprecated Use {@link LineBotClient.getGroupMemberCount} instead.
   * @example
   * // Before:
   * client.getGroupMembersCount(groupId);
   * // After:
   * lineBotClient.getGroupMemberCount(groupId);
   */
  public async getGroupMembersCount(
    groupId: string,
  ): Promise<Types.MembersCountResponse> {
    const groupMemberCount = await this.http.get<Types.MembersCountResponse>(
      `${MESSAGING_API_PREFIX}/group/${groupId}/members/count`,
    );
    return ensureJSON(groupMemberCount);
  }

  /**
   * @deprecated Use {@link LineBotClient.getRoomMemberCount} instead.
   * @example
   * // Before:
   * client.getRoomMembersCount(roomId);
   * // After:
   * lineBotClient.getRoomMemberCount(roomId);
   */
  public async getRoomMembersCount(
    roomId: string,
  ): Promise<Types.MembersCountResponse> {
    const roomMemberCount = await this.http.get<Types.MembersCountResponse>(
      `${MESSAGING_API_PREFIX}/room/${roomId}/members/count`,
    );
    return ensureJSON(roomMemberCount);
  }

  /**
   * @deprecated Use {@link LineBotClient.getGroupSummary} instead.
   * @example
   * // Before:
   * client.getGroupSummary(groupId);
   * // After:
   * lineBotClient.getGroupSummary(groupId);
   */
  public async getGroupSummary(
    groupId: string,
  ): Promise<Types.GroupSummaryResponse> {
    const groupSummary = await this.http.get<Types.GroupSummaryResponse>(
      `${MESSAGING_API_PREFIX}/group/${groupId}/summary`,
    );
    return ensureJSON(groupSummary);
  }

  /**
   * @deprecated Use {@link LineBotClient.getMessageContent} instead.
   * @example
   * // Before:
   * client.getMessageContent(messageId);
   * // After:
   * lineBotClient.getMessageContent(messageId);
   */
  public async getMessageContent(messageId: string): Promise<Readable> {
    return this.http.getStream(
      `${DATA_API_PREFIX}/message/${messageId}/content`,
    );
  }

  private leaveChat(chatType: ChatType, chatId: string): Promise<any> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/${chatType}/${chatId}/leave`,
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.leaveGroup} instead.
   * @example
   * // Before:
   * client.leaveGroup(groupId);
   * // After:
   * lineBotClient.leaveGroup(groupId);
   */
  public async leaveGroup(groupId: string): Promise<any> {
    return this.leaveChat("group", groupId);
  }

  /**
   * @deprecated Use {@link LineBotClient.leaveRoom} instead.
   * @example
   * // Before:
   * client.leaveRoom(roomId);
   * // After:
   * lineBotClient.leaveRoom(roomId);
   */
  public async leaveRoom(roomId: string): Promise<any> {
    return this.leaveChat("room", roomId);
  }

  /**
   * @deprecated Use {@link LineBotClient.getRichMenu} instead.
   * @example
   * // Before:
   * client.getRichMenu(richMenuId);
   * // After:
   * lineBotClient.getRichMenu(richMenuId);
   */
  public async getRichMenu(
    richMenuId: string,
  ): Promise<Types.RichMenuResponse> {
    const res = await this.http.get<Types.RichMenuResponse>(
      `${MESSAGING_API_PREFIX}/richmenu/${richMenuId}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.createRichMenu} instead. Note: return type changed from `string` to `RichMenuIdResponse`.
   * @example
   * // Before:
   * client.createRichMenu(richMenu);
   * // After:
   * lineBotClient.createRichMenu(richMenu);
   */
  public async createRichMenu(richMenu: Types.RichMenu): Promise<string> {
    const res = await this.http.post<any>(
      `${MESSAGING_API_PREFIX}/richmenu`,
      richMenu,
    );
    return ensureJSON(res).richMenuId;
  }

  /**
   * @deprecated Use {@link LineBotClient.deleteRichMenu} instead.
   * @example
   * // Before:
   * client.deleteRichMenu(richMenuId);
   * // After:
   * lineBotClient.deleteRichMenu(richMenuId);
   */
  public async deleteRichMenu(richMenuId: string): Promise<any> {
    return this.http.delete(`${MESSAGING_API_PREFIX}/richmenu/${richMenuId}`);
  }

  /**
   * @deprecated Use {@link LineBotClient.getRichMenuAliasList} instead.
   * @example
   * // Before:
   * client.getRichMenuAliasList();
   * // After:
   * lineBotClient.getRichMenuAliasList();
   */
  public async getRichMenuAliasList(): Promise<Types.GetRichMenuAliasListResponse> {
    const res = await this.http.get<Types.GetRichMenuAliasListResponse>(
      `${MESSAGING_API_PREFIX}/richmenu/alias/list`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getRichMenuAlias} instead.
   * @example
   * // Before:
   * client.getRichMenuAlias(richMenuAliasId);
   * // After:
   * lineBotClient.getRichMenuAlias(richMenuAliasId);
   */
  public async getRichMenuAlias(
    richMenuAliasId: string,
  ): Promise<Types.GetRichMenuAliasResponse> {
    const res = await this.http.get<Types.GetRichMenuAliasResponse>(
      `${MESSAGING_API_PREFIX}/richmenu/alias/${richMenuAliasId}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.createRichMenuAlias} instead.
   * @example
   * // Before:
   * client.createRichMenuAlias(richMenuId, richMenuAliasId);
   * // After:
   * lineBotClient.createRichMenuAlias({ richMenuId, richMenuAliasId });
   */
  public async createRichMenuAlias(
    richMenuId: string,
    richMenuAliasId: string,
  ): Promise<{}> {
    const res = await this.http.post<{}>(
      `${MESSAGING_API_PREFIX}/richmenu/alias`,
      {
        richMenuId,
        richMenuAliasId,
      },
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.deleteRichMenuAlias} instead.
   * @example
   * // Before:
   * client.deleteRichMenuAlias(richMenuAliasId);
   * // After:
   * lineBotClient.deleteRichMenuAlias(richMenuAliasId);
   */
  public async deleteRichMenuAlias(richMenuAliasId: string): Promise<{}> {
    const res = this.http.delete<{}>(
      `${MESSAGING_API_PREFIX}/richmenu/alias/${richMenuAliasId}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.updateRichMenuAlias} instead.
   * @example
   * // Before:
   * client.updateRichMenuAlias(richMenuAliasId, richMenuId);
   * // After:
   * lineBotClient.updateRichMenuAlias(richMenuAliasId, { richMenuId });
   */
  public async updateRichMenuAlias(
    richMenuAliasId: string,
    richMenuId: string,
  ): Promise<{}> {
    const res = await this.http.post<{}>(
      `${MESSAGING_API_PREFIX}/richmenu/alias/${richMenuAliasId}`,
      {
        richMenuId,
      },
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getRichMenuIdOfUser} instead. Note: return type changed from `string` to `RichMenuIdResponse`.
   * @example
   * // Before:
   * client.getRichMenuIdOfUser(userId);
   * // After:
   * lineBotClient.getRichMenuIdOfUser(userId);
   */
  public async getRichMenuIdOfUser(userId: string): Promise<string> {
    const res = await this.http.get<any>(
      `${MESSAGING_API_PREFIX}/user/${userId}/richmenu`,
    );
    return ensureJSON(res).richMenuId;
  }

  /**
   * @deprecated Use {@link LineBotClient.linkRichMenuIdToUser} instead.
   * @example
   * // Before:
   * client.linkRichMenuToUser(userId, richMenuId);
   * // After:
   * lineBotClient.linkRichMenuIdToUser(userId, richMenuId);
   */
  public async linkRichMenuToUser(
    userId: string,
    richMenuId: string,
  ): Promise<any> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/user/${userId}/richmenu/${richMenuId}`,
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.unlinkRichMenuIdFromUser} instead.
   * @example
   * // Before:
   * client.unlinkRichMenuFromUser(userId);
   * // After:
   * lineBotClient.unlinkRichMenuIdFromUser(userId);
   */
  public async unlinkRichMenuFromUser(userId: string): Promise<any> {
    return this.http.delete(`${MESSAGING_API_PREFIX}/user/${userId}/richmenu`);
  }

  /**
   * @deprecated Use {@link LineBotClient.linkRichMenuIdToUsers} instead.
   * @example
   * // Before:
   * client.linkRichMenuToMultipleUsers(richMenuId, userIds);
   * // After:
   * lineBotClient.linkRichMenuIdToUsers({ richMenuId, userIds });
   */
  public async linkRichMenuToMultipleUsers(
    richMenuId: string,
    userIds: string[],
  ): Promise<any> {
    return this.http.post(`${MESSAGING_API_PREFIX}/richmenu/bulk/link`, {
      richMenuId,
      userIds,
    });
  }

  /**
   * @deprecated Use {@link LineBotClient.unlinkRichMenuIdFromUsers} instead.
   * @example
   * // Before:
   * client.unlinkRichMenusFromMultipleUsers(userIds);
   * // After:
   * lineBotClient.unlinkRichMenuIdFromUsers({ userIds });
   */
  public async unlinkRichMenusFromMultipleUsers(
    userIds: string[],
  ): Promise<any> {
    return this.http.post(`${MESSAGING_API_PREFIX}/richmenu/bulk/unlink`, {
      userIds,
    });
  }

  /**
   * @deprecated Use {@link LineBotClient.getRichMenuImage} instead.
   * @example
   * // Before:
   * client.getRichMenuImage(richMenuId);
   * // After:
   * lineBotClient.getRichMenuImage(richMenuId);
   */
  public async getRichMenuImage(richMenuId: string): Promise<Readable> {
    return this.http.getStream(
      `${DATA_API_PREFIX}/richmenu/${richMenuId}/content`,
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.setRichMenuImage} instead. Note: the new method accepts a Blob as the second argument.
   * @example
   * // Before:
   * client.setRichMenuImage(richMenuId, data, contentType);
   * // After:
   * lineBotClient.setRichMenuImage(richMenuId, body);
   */
  public async setRichMenuImage(
    richMenuId: string,
    data: Buffer | Readable,
    contentType?: string,
  ): Promise<any> {
    return this.http.postBinary(
      `${DATA_API_PREFIX}/richmenu/${richMenuId}/content`,
      data,
      contentType,
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.getRichMenuList} instead.
   * @example
   * // Before:
   * client.getRichMenuList();
   * // After:
   * lineBotClient.getRichMenuList();
   */
  public async getRichMenuList(): Promise<Array<Types.RichMenuResponse>> {
    const res = await this.http.get<any>(
      `${MESSAGING_API_PREFIX}/richmenu/list`,
    );
    return ensureJSON(res).richmenus;
  }

  /**
   * @deprecated Use {@link LineBotClient.setDefaultRichMenu} instead.
   * @example
   * // Before:
   * client.setDefaultRichMenu(richMenuId);
   * // After:
   * lineBotClient.setDefaultRichMenu(richMenuId);
   */
  public async setDefaultRichMenu(richMenuId: string): Promise<{}> {
    return this.http.post(
      `${MESSAGING_API_PREFIX}/user/all/richmenu/${richMenuId}`,
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.getDefaultRichMenuId} instead. Note: return type changed from `string` to `RichMenuIdResponse`.
   * @example
   * // Before:
   * client.getDefaultRichMenuId();
   * // After:
   * lineBotClient.getDefaultRichMenuId();
   */
  public async getDefaultRichMenuId(): Promise<string> {
    const res = await this.http.get<any>(
      `${MESSAGING_API_PREFIX}/user/all/richmenu`,
    );
    return ensureJSON(res).richMenuId;
  }

  /**
   * @deprecated Use {@link LineBotClient.cancelDefaultRichMenu} instead.
   * @example
   * // Before:
   * client.deleteDefaultRichMenu();
   * // After:
   * lineBotClient.cancelDefaultRichMenu();
   */
  public async deleteDefaultRichMenu(): Promise<{}> {
    return this.http.delete(`${MESSAGING_API_PREFIX}/user/all/richmenu`);
  }

  /**
   * @deprecated Use {@link LineBotClient.issueLinkToken} instead. Note: return type changed from `string` to `IssueLinkTokenResponse`.
   * @example
   * // Before:
   * client.getLinkToken(userId);
   * // After:
   * lineBotClient.issueLinkToken(userId);
   */
  public async getLinkToken(userId: string): Promise<string> {
    const res = await this.http.post<any>(
      `${MESSAGING_API_PREFIX}/user/${userId}/linkToken`,
    );
    return ensureJSON(res).linkToken;
  }

  /**
   * @deprecated Use {@link LineBotClient.getNumberOfSentReplyMessages} instead.
   * @example
   * // Before:
   * client.getNumberOfSentReplyMessages(date);
   * // After:
   * lineBotClient.getNumberOfSentReplyMessages(date);
   */
  public async getNumberOfSentReplyMessages(
    date: string,
  ): Promise<Types.NumberOfMessagesSentResponse> {
    const res = await this.http.get<Types.NumberOfMessagesSentResponse>(
      `${MESSAGING_API_PREFIX}/message/delivery/reply?date=${date}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getNumberOfSentPushMessages} instead.
   * @example
   * // Before:
   * client.getNumberOfSentPushMessages(date);
   * // After:
   * lineBotClient.getNumberOfSentPushMessages(date);
   */
  public async getNumberOfSentPushMessages(
    date: string,
  ): Promise<Types.NumberOfMessagesSentResponse> {
    const res = await this.http.get<Types.NumberOfMessagesSentResponse>(
      `${MESSAGING_API_PREFIX}/message/delivery/push?date=${date}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getNumberOfSentMulticastMessages} instead.
   * @example
   * // Before:
   * client.getNumberOfSentMulticastMessages(date);
   * // After:
   * lineBotClient.getNumberOfSentMulticastMessages(date);
   */
  public async getNumberOfSentMulticastMessages(
    date: string,
  ): Promise<Types.NumberOfMessagesSentResponse> {
    const res = await this.http.get<Types.NumberOfMessagesSentResponse>(
      `${MESSAGING_API_PREFIX}/message/delivery/multicast?date=${date}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getNarrowcastProgress} instead.
   * @example
   * // Before:
   * client.getNarrowcastProgress(requestId);
   * // After:
   * lineBotClient.getNarrowcastProgress(requestId);
   */
  public async getNarrowcastProgress(
    requestId: string,
  ): Promise<Types.NarrowcastProgressResponse> {
    const res = await this.http.get<Types.NarrowcastProgressResponse>(
      `${MESSAGING_API_PREFIX}/message/progress/narrowcast?requestId=${requestId}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getMessageQuota} instead.
   * @example
   * // Before:
   * client.getTargetLimitForAdditionalMessages();
   * // After:
   * lineBotClient.getMessageQuota();
   */
  public async getTargetLimitForAdditionalMessages(): Promise<Types.TargetLimitForAdditionalMessages> {
    const res = await this.http.get<Types.TargetLimitForAdditionalMessages>(
      `${MESSAGING_API_PREFIX}/message/quota`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getMessageQuotaConsumption} instead.
   * @example
   * // Before:
   * client.getNumberOfMessagesSentThisMonth();
   * // After:
   * lineBotClient.getMessageQuotaConsumption();
   */
  public async getNumberOfMessagesSentThisMonth(): Promise<Types.NumberOfMessagesSentThisMonth> {
    const res = await this.http.get<Types.NumberOfMessagesSentThisMonth>(
      `${MESSAGING_API_PREFIX}/message/quota/consumption`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getNumberOfSentBroadcastMessages} instead.
   * @example
   * // Before:
   * client.getNumberOfSentBroadcastMessages(date);
   * // After:
   * lineBotClient.getNumberOfSentBroadcastMessages(date);
   */
  public async getNumberOfSentBroadcastMessages(
    date: string,
  ): Promise<Types.NumberOfMessagesSentResponse> {
    const res = await this.http.get<Types.NumberOfMessagesSentResponse>(
      `${MESSAGING_API_PREFIX}/message/delivery/broadcast?date=${date}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getNumberOfMessageDeliveries} instead.
   * @example
   * // Before:
   * client.getNumberOfMessageDeliveries(date);
   * // After:
   * lineBotClient.getNumberOfMessageDeliveries(date);
   */
  public async getNumberOfMessageDeliveries(
    date: string,
  ): Promise<Types.NumberOfMessageDeliveriesResponse> {
    const res = await this.http.get<Types.NumberOfMessageDeliveriesResponse>(
      `${MESSAGING_API_PREFIX}/insight/message/delivery?date=${date}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getNumberOfFollowers} instead. Note: `date` is now optional.
   * @example
   * // Before:
   * client.getNumberOfFollowers(date);
   * // After:
   * lineBotClient.getNumberOfFollowers(date);
   */
  public async getNumberOfFollowers(
    date: string,
  ): Promise<Types.NumberOfFollowersResponse> {
    const res = await this.http.get<Types.NumberOfFollowersResponse>(
      `${MESSAGING_API_PREFIX}/insight/followers?date=${date}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getFriendsDemographics} instead.
   * @example
   * // Before:
   * client.getFriendDemographics();
   * // After:
   * lineBotClient.getFriendsDemographics();
   */
  public async getFriendDemographics(): Promise<Types.FriendDemographics> {
    const res = await this.http.get<Types.FriendDemographics>(
      `${MESSAGING_API_PREFIX}/insight/demographic`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getMessageEvent} instead.
   * @example
   * // Before:
   * client.getUserInteractionStatistics(requestId);
   * // After:
   * lineBotClient.getMessageEvent(requestId);
   */
  public async getUserInteractionStatistics(
    requestId: string,
  ): Promise<Types.UserInteractionStatistics> {
    const res = await this.http.get<Types.UserInteractionStatistics>(
      `${MESSAGING_API_PREFIX}/insight/message/event?requestId=${requestId}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getStatisticsPerUnit} instead.
   * @example
   * // Before:
   * client.getStatisticsPerUnit(unit, from, to);
   * // After:
   * lineBotClient.getStatisticsPerUnit(unit, from, to);
   */
  public async getStatisticsPerUnit(
    customAggregationUnit: string,
    from: string,
    to: string,
  ): Promise<Types.StatisticsPerUnit> {
    const res = await this.http.get<Types.StatisticsPerUnit>(
      `${MESSAGING_API_PREFIX}/insight/message/event/aggregation?customAggregationUnit=${customAggregationUnit}&from=${from}&to=${to}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.createAudienceGroup} instead.
   * @example
   * // Before:
   * client.createUploadAudienceGroup({...});
   * // After:
   * lineBotClient.createAudienceGroup({...});
   */
  public async createUploadAudienceGroup(uploadAudienceGroup: {
    description: string;
    isIfaAudience?: boolean;
    audiences?: { id: string }[];
    uploadDescription?: string;
  }) {
    const res = await this.http.post<{
      audienceGroupId: number;
      type: string;
      description: string;
      created: number;
    }>(`${MESSAGING_API_PREFIX}/audienceGroup/upload`, {
      ...uploadAudienceGroup,
    });
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.createAudienceForUploadingUserIds} instead.
   * @example
   * // Before:
   * client.createUploadAudienceGroupByFile({ ..., file });
   * // After:
   * lineBotClient.createAudienceForUploadingUserIds(file, description, isIfaAudience, uploadDescription);
   */
  public async createUploadAudienceGroupByFile(uploadAudienceGroup: {
    description: string;
    isIfaAudience?: boolean;
    uploadDescription?: string;
    file: Buffer | Readable;
  }) {
    const file = await this.http.toBuffer(uploadAudienceGroup.file);
    const body = createMultipartFormData({ ...uploadAudienceGroup, file });
    const res = await this.http.postFormMultipart<{
      audienceGroupId: number;
      type: "UPLOAD";
      description: string;
      created: number;
    }>(`${DATA_API_PREFIX}/audienceGroup/upload/byFile`, body);
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.addAudienceToAudienceGroup} instead.
   * Note: if you were passing `description`, you must also call
   * {@link LineBotClient.updateAudienceGroupDescription} separately, as
   * `AddAudienceToAudienceGroupRequest` does not accept a `description` field.
   * @example
   * // Before:
   * client.updateUploadAudienceGroup({ audienceGroupId, description, uploadDescription, audiences });
   * // After (two calls required when description is used):
   * await lineBotClient.addAudienceToAudienceGroup({ audienceGroupId, uploadDescription, audiences });
   * await lineBotClient.updateAudienceGroupDescription(audienceGroupId, { description });
   */
  public async updateUploadAudienceGroup(
    uploadAudienceGroup: {
      audienceGroupId: number;
      description?: string;
      uploadDescription?: string;
      audiences: { id: string }[];
    },
    // for set request timeout
    httpConfig?: Partial<AxiosRequestConfig>,
  ) {
    const res = await this.http.put<{}>(
      `${MESSAGING_API_PREFIX}/audienceGroup/upload`,
      {
        ...uploadAudienceGroup,
      },
      httpConfig,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.addUserIdsToAudience} instead.
   * @example
   * // Before:
   * client.updateUploadAudienceGroupByFile({ ..., file });
   * // After:
   * lineBotClient.addUserIdsToAudience(file, audienceGroupId, uploadDescription);
   */
  public async updateUploadAudienceGroupByFile(
    uploadAudienceGroup: {
      audienceGroupId: number;
      uploadDescription?: string;
      file: Buffer | Readable;
    },
    // for set request timeout
    httpConfig?: Partial<AxiosRequestConfig>,
  ) {
    const file = await this.http.toBuffer(uploadAudienceGroup.file);
    const body = createMultipartFormData({ ...uploadAudienceGroup, file });

    const res = await this.http.putFormMultipart<{}>(
      `${DATA_API_PREFIX}/audienceGroup/upload/byFile`,
      body,
      httpConfig,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.createClickBasedAudienceGroup} instead.
   * @example
   * // Before:
   * client.createClickAudienceGroup({...});
   * // After:
   * lineBotClient.createClickBasedAudienceGroup({...});
   */
  public async createClickAudienceGroup(clickAudienceGroup: {
    description: string;
    requestId: string;
    clickUrl?: string;
  }) {
    const res = await this.http.post<
      {
        audienceGroupId: number;
        type: string;
        created: number;
      } & typeof clickAudienceGroup
    >(`${MESSAGING_API_PREFIX}/audienceGroup/click`, {
      ...clickAudienceGroup,
    });
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.createImpBasedAudienceGroup} instead.
   * @example
   * // Before:
   * client.createImpAudienceGroup({...});
   * // After:
   * lineBotClient.createImpBasedAudienceGroup({...});
   */
  public async createImpAudienceGroup(impAudienceGroup: {
    requestId: string;
    description: string;
  }) {
    const res = await this.http.post<
      {
        audienceGroupId: number;
        type: string;
        created: number;
      } & typeof impAudienceGroup
    >(`${MESSAGING_API_PREFIX}/audienceGroup/imp`, {
      ...impAudienceGroup,
    });
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.updateAudienceGroupDescription} instead. Note: argument order changed and `audienceGroupId` is now a number.
   * @example
   * // Before:
   * client.setDescriptionAudienceGroup(description, audienceGroupId);
   * // After:
   * lineBotClient.updateAudienceGroupDescription(audienceGroupId, { description });
   */
  public async setDescriptionAudienceGroup(
    description: string,
    audienceGroupId: string,
  ) {
    const res = await this.http.put<{}>(
      `${MESSAGING_API_PREFIX}/audienceGroup/${audienceGroupId}/updateDescription`,
      {
        description,
      },
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.deleteAudienceGroup} instead. Note: `audienceGroupId` is now a number.
   * @example
   * // Before:
   * client.deleteAudienceGroup(audienceGroupId);
   * // After:
   * lineBotClient.deleteAudienceGroup(audienceGroupId);
   */
  public async deleteAudienceGroup(audienceGroupId: string) {
    const res = await this.http.delete<{}>(
      `${MESSAGING_API_PREFIX}/audienceGroup/${audienceGroupId}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getAudienceData} instead. Note: `audienceGroupId` is now a number.
   * @example
   * // Before:
   * client.getAudienceGroup(audienceGroupId);
   * // After:
   * lineBotClient.getAudienceData(audienceGroupId);
   */
  public async getAudienceGroup(audienceGroupId: string) {
    const res = await this.http.get<Types.AudienceGroup>(
      `${MESSAGING_API_PREFIX}/audienceGroup/${audienceGroupId}`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getAudienceGroups} instead. Note: the last two argument positions are swapped.
   * @example
   * // Before:
   * client.getAudienceGroups(page, description, status, size, createRoute, includesExternalPublicGroups);
   * // After:
   * lineBotClient.getAudienceGroups(page, description, status, size, includesExternalPublicGroups, createRoute);
   */
  public async getAudienceGroups(
    page: number,
    description?: string,
    status?: Types.AudienceGroupStatus,
    size?: number,
    createRoute?: Types.AudienceGroupCreateRoute,
    includesExternalPublicGroups?: boolean,
  ) {
    const res = await this.http.get<{
      audienceGroups: Types.AudienceGroups;
      hasNextPage: boolean;
      totalCount: number;
      readWriteAudienceGroupTotalCount: number;
      page: number;
      size: number;
    }>(`${MESSAGING_API_PREFIX}/audienceGroup/list`, {
      page,
      description,
      status,
      size,
      createRoute,
      includesExternalPublicGroups,
    });
    return ensureJSON(res);
  }

  /**
   * @deprecated No direct equivalent in LineBotClient. See docs/guide/migration.md for details.
   */
  public async getAudienceGroupAuthorityLevel() {
    const res = await this.http.get<{
      authorityLevel: Types.AudienceGroupAuthorityLevel;
    }>(`${MESSAGING_API_PREFIX}/audienceGroup/authorityLevel`);
    return ensureJSON(res);
  }

  /**
   * @deprecated No direct equivalent in LineBotClient. See docs/guide/migration.md for details.
   */
  public async changeAudienceGroupAuthorityLevel(
    authorityLevel: Types.AudienceGroupAuthorityLevel,
  ) {
    const res = await this.http.put<{}>(
      `${MESSAGING_API_PREFIX}/audienceGroup/authorityLevel`,
      { authorityLevel },
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.getBotInfo} instead.
   * @example
   * // Before:
   * client.getBotInfo();
   * // After:
   * lineBotClient.getBotInfo();
   */
  public async getBotInfo(): Promise<Types.BotInfoResponse> {
    const res = await this.http.get<Types.BotInfoResponse>(
      `${MESSAGING_API_PREFIX}/info`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.setWebhookEndpoint} instead.
   * @example
   * // Before:
   * client.setWebhookEndpointUrl(endpoint);
   * // After:
   * lineBotClient.setWebhookEndpoint({ endpoint });
   */
  public async setWebhookEndpointUrl(endpoint: string) {
    return this.http.put<{}>(
      `${MESSAGING_API_PREFIX}/channel/webhook/endpoint`,
      { endpoint },
    );
  }

  /**
   * @deprecated Use {@link LineBotClient.getWebhookEndpoint} instead.
   * @example
   * // Before:
   * client.getWebhookEndpointInfo();
   * // After:
   * lineBotClient.getWebhookEndpoint();
   */
  public async getWebhookEndpointInfo() {
    const res = await this.http.get<Types.WebhookEndpointInfoResponse>(
      `${MESSAGING_API_PREFIX}/channel/webhook/endpoint`,
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.testWebhookEndpoint} instead.
   * @example
   * // Before:
   * client.testWebhookEndpoint(endpoint);
   * // After:
   * lineBotClient.testWebhookEndpoint({ endpoint });
   */
  public async testWebhookEndpoint(endpoint?: string) {
    const res = await this.http.post<Types.TestWebhookEndpointResponse>(
      `${MESSAGING_API_PREFIX}/channel/webhook/test`,
      { endpoint },
    );
    return ensureJSON(res);
  }

  /**
   * @deprecated Use {@link LineBotClient.validateRichMenuObject} instead.
   * @example
   * // Before:
   * client.validateRichMenu(richMenu);
   * // After:
   * lineBotClient.validateRichMenuObject(richMenu);
   */
  public async validateRichMenu(richMenu: Types.RichMenu): Promise<{}> {
    return await this.http.post<{}>(
      `${MESSAGING_API_PREFIX}/richmenu/validate`,
      richMenu,
    );
  }
}

/**
 * @deprecated Use `channelAccessToken.ChannelAccessTokenClient` instead. See docs/guide/migration.md for the method mapping.
 */
export class OAuth {
  private http: HTTPClient;

  constructor() {
    this.http = new HTTPClient();
  }

  /**
   * @deprecated Use {@link channelAccessToken.ChannelAccessTokenClient.issueChannelToken} instead.
   * @example
   * // Before:
   * oauth.issueAccessToken(client_id, client_secret);
   * // After:
   * const oauthClient = new channelAccessToken.ChannelAccessTokenClient({});
   * oauthClient.issueChannelToken('client_credentials', client_id, client_secret);
   */
  public issueAccessToken(
    client_id: string,
    client_secret: string,
  ): Promise<Types.ChannelAccessToken> {
    return this.http.postForm(`${OAUTH_BASE_PREFIX}/accessToken`, {
      grant_type: "client_credentials",
      client_id,
      client_secret,
    });
  }

  /**
   * @deprecated Use {@link channelAccessToken.ChannelAccessTokenClient.revokeChannelToken} instead.
   * @example
   * // Before:
   * oauth.revokeAccessToken(access_token);
   * // After:
   * const oauthClient = new channelAccessToken.ChannelAccessTokenClient({});
   * oauthClient.revokeChannelToken(access_token);
   */
  public revokeAccessToken(access_token: string): Promise<{}> {
    return this.http.postForm(`${OAUTH_BASE_PREFIX}/revoke`, { access_token });
  }

  /**
   * @deprecated Use {@link channelAccessToken.ChannelAccessTokenClient.verifyChannelTokenByJWT} instead.
   * @example
   * // Before:
   * oauth.verifyAccessToken(access_token);
   * // After:
   * const oauthClient = new channelAccessToken.ChannelAccessTokenClient({});
   * oauthClient.verifyChannelTokenByJWT(access_token);
   */
  public verifyAccessToken(
    access_token: string,
  ): Promise<Types.VerifyAccessToken> {
    return this.http.get(`${OAUTH_BASE_PREFIX_V2_1}/verify`, { access_token });
  }

  /**
   * @deprecated No direct equivalent in LineBotClient. See docs/guide/migration.md for details.
   */
  public verifyIdToken(
    id_token: string,
    client_id: string,
    nonce?: string,
    user_id?: string,
  ): Promise<Types.VerifyIDToken> {
    const body: { [key: string]: string } = {
      id_token,
      client_id,
    };

    if (nonce) {
      body.nonce = nonce;
    }

    if (user_id) {
      body.user_id = user_id;
    }
    return this.http.postForm(`${OAUTH_BASE_PREFIX_V2_1}/verify`, body);
  }

  /**
   * @deprecated Use {@link channelAccessToken.ChannelAccessTokenClient.issueChannelTokenByJWT} instead.
   * @example
   * // Before:
   * oauth.issueChannelAccessTokenV2_1(client_assertion);
   * // After:
   * const oauthClient = new channelAccessToken.ChannelAccessTokenClient({});
   * oauthClient.issueChannelTokenByJWT('client_credentials', 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer', client_assertion);
   */
  public issueChannelAccessTokenV2_1(
    client_assertion: string,
  ): Promise<Types.ChannelAccessToken> {
    return this.http.postForm(`${OAUTH_BASE_PREFIX_V2_1}/token`, {
      grant_type: "client_credentials",
      client_assertion_type:
        "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
      client_assertion,
    });
  }

  /**
   * @deprecated Use {@link channelAccessToken.ChannelAccessTokenClient.getsAllValidChannelAccessTokenKeyIds} instead.
   * @example
   * // Before:
   * oauth.getChannelAccessTokenKeyIdsV2_1(client_assertion);
   * // After:
   * const oauthClient = new channelAccessToken.ChannelAccessTokenClient({});
   * oauthClient.getsAllValidChannelAccessTokenKeyIds('urn:ietf:params:oauth:client-assertion-type:jwt-bearer', client_assertion);
   */
  public getChannelAccessTokenKeyIdsV2_1(
    client_assertion: string,
  ): Promise<{ key_ids: string[] }> {
    return this.http.get(`${OAUTH_BASE_PREFIX_V2_1}/tokens/kid`, {
      client_assertion_type:
        "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
      client_assertion,
    });
  }

  /**
   * @deprecated Use {@link channelAccessToken.ChannelAccessTokenClient.revokeChannelTokenByJWT} instead.
   * @example
   * // Before:
   * oauth.revokeChannelAccessTokenV2_1(client_id, client_secret, access_token);
   * // After:
   * const oauthClient = new channelAccessToken.ChannelAccessTokenClient({});
   * oauthClient.revokeChannelTokenByJWT(client_id, client_secret, access_token);
   */
  public revokeChannelAccessTokenV2_1(
    client_id: string,
    client_secret: string,
    access_token: string,
  ): Promise<{}> {
    return this.http.postForm(`${OAUTH_BASE_PREFIX_V2_1}/revoke`, {
      client_id,
      client_secret,
      access_token,
    });
  }
}
