/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-locals */
import { GetMessageContentTranscodingResponse } from "../model/getMessageContentTranscodingResponse";

import * as Types from "../../types";
import { ensureJSON } from "../../utils";
import { Readable } from "stream";

import HTTPClient from "../../http";

const pkg = require("../../../package.json");

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

interface httpClientConfig {
  baseURL?: string;
  channelAccessToken: string;
  // TODO support defaultHeaders?
}

export class MessagingApiBlobClient {
  private config: httpClientConfig;

  constructor(config: httpClientConfig) {
    this.config = {
      baseURL: "https://api-data.line.me",
      ...config,
    };
  }

  /**
   * Download image, video, and audio data sent from users.
   * @param messageId Message ID of video or audio
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-content"> Documentation</a>
   */
  public async getMessageContent(
    messageId: string,
  ): Promise<ReadableStreamDefaultReader<Uint8Array>> {
    const requestUrl = new URL(
      "/v2/bot/message/{messageId}/content".replace(
        "{" + "messageId" + "}",
        String(messageId),
      ),
      this.config.baseURL,
    );

    const resp = await fetch(requestUrl, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },
    });

    return resp.body.getReader();
  }
  /**
   * Get a preview image of the image or video
   * @param messageId Message ID of image or video
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#get-image-or-video-preview"> Documentation</a>
   */
  public async getMessageContentPreview(
    messageId: string,
  ): Promise<ReadableStreamDefaultReader<Uint8Array>> {
    const requestUrl = new URL(
      "/v2/bot/message/{messageId}/content/preview".replace(
        "{" + "messageId" + "}",
        String(messageId),
      ),
      this.config.baseURL,
    );

    const resp = await fetch(requestUrl, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },
    });

    return resp.body.getReader();
  }
  /**
   * Verify the preparation status of a video or audio for getting
   * @param messageId Message ID of video or audio
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#verify-video-or-audio-preparation-status"> Documentation</a>
   */
  public async getMessageContentTranscodingByMessageId(
    messageId: string,
  ): Promise<GetMessageContentTranscodingResponse> {
    const requestUrl = new URL(
      "/v2/bot/message/{messageId}/content/transcoding".replace(
        "{" + "messageId" + "}",
        String(messageId),
      ),
      this.config.baseURL,
    );

    const resp = await fetch(requestUrl, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },
    });

    const resBody = await resp.json();

    // for backward compatibility, inject x-line-request-id to response body.
    const { LINE_REQUEST_ID_HTTP_HEADER_NAME } = Types;
    const requestIdHeader = resp.headers.get(LINE_REQUEST_ID_HTTP_HEADER_NAME);
    if (requestIdHeader) {
      resBody[LINE_REQUEST_ID_HTTP_HEADER_NAME] = requestIdHeader;
    }

    return resBody;
  }
  /**
   * Download rich menu image.
   * @param richMenuId ID of the rich menu with the image to be downloaded
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#download-rich-menu-image"> Documentation</a>
   */
  public async getRichMenuImage(
    richMenuId: string,
  ): Promise<ReadableStreamDefaultReader<Uint8Array>> {
    const requestUrl = new URL(
      "/v2/bot/richmenu/{richMenuId}/content".replace(
        "{" + "richMenuId" + "}",
        String(richMenuId),
      ),
      this.config.baseURL,
    );

    const resp = await fetch(requestUrl, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },
    });

    return resp.body.getReader();
  }
  /**
   * Upload rich menu image
   * @param richMenuId The ID of the rich menu to attach the image to
   * @param body
   *
   * @see <a href="https://developers.line.biz/en/reference/messaging-api/#upload-rich-menu-image"> Documentation</a>
   */
  public async setRichMenuImage(
    richMenuId: string,
    body?: Blob,
  ): Promise<Types.MessageAPIResponseBase> {
    const requestUrl = new URL(
      "/v2/bot/richmenu/{richMenuId}/content".replace(
        "{" + "richMenuId" + "}",
        String(richMenuId),
      ),
      this.config.baseURL,
    );

    const resp = await fetch(requestUrl, {
      method: "POST",
      headers: {
        Authorization: "Bearer " + this.config.channelAccessToken,
        "User-Agent": `${pkg.name}/${pkg.version}`,
      },

      body: body,
    });

    const resBody = await resp.json();

    // for backward compatibility, inject x-line-request-id to response body.
    const { LINE_REQUEST_ID_HTTP_HEADER_NAME } = Types;
    const requestIdHeader = resp.headers.get(LINE_REQUEST_ID_HTTP_HEADER_NAME);
    if (requestIdHeader) {
      resBody[LINE_REQUEST_ID_HTTP_HEADER_NAME] = requestIdHeader;
    }

    return resBody;
  }
}
