/**
 * LIFF server API
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @see <a href="https://developers.line.biz/en/reference/liff-server/#add-liff-app">https://developers.line.biz/en/reference/liff-server/#add-liff-app</a>
 */
export type AddLiffAppResponse = {
  liffId: string;
};
