/**
 * LIFF server API
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestFile } from './models';


export type LiffView = {
    /**
    * Size of the LIFF app view. Specify one of these values: - compact - tall - full 
    */
    'type': LiffView.TypeEnum/**/;
    /**
    * Endpoint URL. This is the URL of the web app that implements the LIFF app (e.g. https://example.com). Used when the LIFF app is launched using the LIFF URL. The URL scheme must be https. URL fragments (#URL-fragment) can\'t be specified. 
    */
    'url': string/**/;
    /**
    * `true` to use the LIFF app in modular mode. When in modular mode, the action button in the header is not displayed. 
    */
    'moduleMode'?: boolean/**/;
}

export namespace LiffView {
    export enum TypeEnum {
        Compact = <any> 'compact',
        Tall = <any> 'tall',
        Full = <any> 'full'
    }
}
