/**
 * LIFF server API
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @see <a href="https://developers.line.biz/en/reference/liff-server/#get-all-liff-apps">https://developers.line.biz/en/reference/liff-server/#get-all-liff-apps</a>
 */
export type LiffFeatures = {
  /**
   * `true` if the LIFF app supports Bluetooth® Low Energy for LINE Things. `false` otherwise.
   */
  ble?: boolean;
  /**
   * `true` to use the 2D code reader in the LIFF app. false otherwise. The default value is `false`.
   * @default false
   */
  qrCode?: boolean;
};
