name: Changelog CI

# Controls when the action will run. Triggers the workflow on a pull request
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Run Changelog CI & Bump npm version
        run: npm run generate-changelog

      - name: Config Internal Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Copy & Deploy
        run: |
          git add -A
          git commit -m '(Changelog CI) Added Changelog'
          git push