name: Deploy Docs

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Dependency
      run: npm ci
    - name: Config Internal Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Clone Doc History
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'doc-dist'
    - name: Clean Doc Directory
      run: |
        cd doc-dist
        ls | grep -v '.git' | xargs rm -r
        cd ../
    - name: Build Docs
      run: npm run docs:build
    - name: Copy & Deploy
      run: |
        cp -r docs/.vuepress/dist/* doc-dist/
        cd doc-dist
        git add -A
        git commit -m 'Deploy docs'
        git push
