name: Test

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        # https://nodejs.org/en/about/releases/
        node:
          - '22'
          - '24'
          - '26'
      fail-fast: false

    name: Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - name: Set up Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install Dependency
        run: npm ci
      - name: Test generator
        run: cd generator; mvn package; cd ..
      - name: Generate code
        run: |
          python3 generate-code.py
      - name: Run all checks
        run: npm run checkAll

  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          skip_push: "true"
